"""Resume schemas — variants, immutable versions, and the structured document itself.

Golden rule #6 of ``docs/CONTRACTS.md`` §18 shapes this module: a resume is a *generated
view* of the knowledge graph, never a stored file. So:

* :class:`ResumeRead` / :class:`ResumeCreate` describe a **variant** — a name, a template, and
  generation config. A variant holds no resume content at all.
* :class:`ResumeVersionRead` describes one **immutable generation**: the structured document
  that was produced, the :class:`~app.models.knowledge.KnowledgeFact` ids every bullet traces
  back to, the token cost, and the model's reasoning. ``content_json`` is retained forever;
  the rendered PDF is disposable and ``file_id`` goes NULL when cleanup reclaims it.
* :class:`ResumeDocumentSchema` and its parts mirror ``app/documents/models.py``.

**The mirror is deliberately self-contained.** This module does not import
:mod:`app.documents`, because ``app.schemas`` sits below the document renderer in the
dependency graph: the API layer must be importable without pulling in LaTeX, DOCX and HTML
machinery. The shape is defined by ``docs/CONTRACTS.md`` §11 —
``ResumeDocument(contact, summary, sections, skills_line, meta)`` over
``ResumeSection(heading, entries)`` over ``ResumeEntry(title, organization, location,
date_range, bullets, fact_ids)``.

Every field of the document mirror carries a default. A version generated by an older build
must still deserialise, and a read model that raises on historical data would make the audit
trail unreadable exactly when it matters.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Final, Literal

from pydantic import Field

from app.schemas.common import Schema

__all__ = [
    "DEFAULT_RENDER_FORMAT",
    "DEFAULT_RESUME_TEMPLATE",
    "RenderFormat",
    "ResumeContactSchema",
    "ResumeCreate",
    "ResumeDocumentSchema",
    "ResumeEntrySchema",
    "ResumePreviewRequest",
    "ResumeRead",
    "ResumeSectionSchema",
    "ResumeVersionRead",
]

#: Output formats the template plugins can render (``docs/CONTRACTS.md`` §11).
RenderFormat = Literal["pdf", "docx", "md", "html"]

#: Format used when a caller does not name one.
DEFAULT_RENDER_FORMAT: Final[str] = "pdf"

#: Template used when neither the variant nor the request names one. Mirrors
#: ``settings.resume_template`` and ``UserPreferences.resume_template``.
DEFAULT_RESUME_TEMPLATE: Final[str] = "modern"

#: Upper bound on bullets a single tailoring pass may select. Beyond this the shrink loop
#: cannot fit one page regardless of font size, so accepting a larger value would only
#: guarantee wasted generation tokens.
MAX_TAILOR_BULLETS: Final[int] = 60

#: Default bullet budget, mirroring ``TailorRequest.max_bullets``.
DEFAULT_TAILOR_BULLETS: Final[int] = 18

# -- page-fit estimation ----------------------------------------------------------------
# ``estimated_lines`` exists so the shrink loop can reject an over-long document *before*
# paying to render it. These constants describe a single-column resume at 10.5pt with
# 0.5in margins, which is the starting point of that loop.

#: Characters that fit on one rendered line at the default font size and margins.
CHARS_PER_LINE: Final[int] = 95

#: Lines consumed by the contact header block (name, contact row, spacing).
HEADER_LINES: Final[int] = 3

#: Lines consumed by a section heading and the rule beneath it.
SECTION_HEADING_LINES: Final[int] = 2

#: Lines consumed by an entry's title/organisation/date row before its bullets.
ENTRY_HEADER_LINES: Final[int] = 1


def _wrapped_lines(text: str) -> int:
    """Return how many rendered lines *text* occupies at :data:`CHARS_PER_LINE`.

    Args:
        text: A summary, bullet, or skills line.

    Returns:
        At least 1 for any non-empty string, 0 for an empty one.
    """
    length = len(text.strip())
    if length == 0:
        return 0
    return -(-length // CHARS_PER_LINE)  # ceiling division without importing math


# ======================================================================================
# Document mirror (shape of ResumeVersion.content_json)
# ======================================================================================


class ResumeContactSchema(Schema):
    """The header block of a generated resume.

    Populated from :class:`~app.models.user.User` and
    :class:`~app.models.profile.UserProfile`, never from a model: a fabricated email address
    or phone number would be the most damaging hallucination this system could produce.
    """

    name: str = Field(default="", description="Full name, as printed at the top.")
    email: str | None = None
    phone: str | None = None
    location: str | None = None
    website: str | None = None
    github: str | None = None
    linkedin: str | None = None
    portfolio: str | None = None
    links: dict[str, str] = Field(
        default_factory=dict,
        description="Additional labelled URLs with no named slot.",
    )


class ResumeEntrySchema(Schema):
    """One experience, project, or education entry.

    ``fact_ids`` is the audit trail: every bullet in ``bullets`` corresponds to a
    :class:`~app.models.knowledge.KnowledgeFact` id here. A bullet with no traceable fact is
    a bug (golden rule #7), which is only detectable because the ids travel with the text.
    ``organization``, ``role`` and ``date_range`` are copied verbatim from the source facts —
    never written by the model.
    """

    title: str = Field(default="", description="Role title or project name.")
    organization: str | None = Field(
        default=None,
        description="Employer, school, or project owner. Copied from the source fact.",
    )
    location: str | None = None
    date_range: str | None = Field(
        default=None,
        description='As written by the source ("Jun 2024 - Present"); never re-parsed.',
    )
    bullets: list[str] = Field(default_factory=list)
    fact_ids: list[str] = Field(
        default_factory=list,
        description="KnowledgeFact ids backing `bullets`; the anti-hallucination trail.",
    )


class ResumeSectionSchema(Schema):
    """A titled group of entries — "Experience", "Projects", "Education"."""

    heading: str = Field(default="", description="Section heading as printed.")
    entries: list[ResumeEntrySchema] = Field(default_factory=list)


class ResumeDocumentSchema(Schema):
    """The structured resume — the permanent form stored in ``ResumeVersion.content_json``.

    Mirrors ``app.documents.models.ResumeDocument`` without importing it, so the API layer
    stays independent of the rendering stack. The rendered artifact is disposable; this is
    the canonical record and it is retained forever.
    """

    contact: ResumeContactSchema = Field(default_factory=ResumeContactSchema)
    summary: str | None = Field(
        default=None,
        description="Optional opening paragraph, itself assembled from facts.",
    )
    sections: list[ResumeSectionSchema] = Field(default_factory=list)
    skills_line: str | None = Field(
        default=None,
        description="Flat skills list rendered as a single line for ATS parsers.",
    )
    meta: dict[str, Any] = Field(
        default_factory=dict,
        description="Generation metadata: template, posting id, model, timestamps.",
    )

    def total_bullets(self) -> int:
        """Count every bullet across every entry of every section.

        Returns:
            The total number of bullets in the document.
        """
        return sum(len(entry.bullets) for section in self.sections for entry in section.entries)

    def estimated_lines(self) -> int:
        """Estimate how many rendered lines this document occupies.

        Used by the renderer's page-fit shrink loop to reject an over-long document before
        paying to typeset it. The estimate is intentionally simple and slightly pessimistic:
        a false "too long" costs one extra shrink iteration, while a false "fits" costs a
        wasted render and a two-page resume.

        Returns:
            The estimated line count, including headers and section furniture.
        """
        lines = HEADER_LINES
        if self.summary:
            lines += _wrapped_lines(self.summary)
        for section in self.sections:
            lines += SECTION_HEADING_LINES
            for entry in section.entries:
                lines += ENTRY_HEADER_LINES
                for bullet in entry.bullets:
                    lines += _wrapped_lines(bullet)
        if self.skills_line:
            lines += _wrapped_lines(self.skills_line)
        return lines


# ======================================================================================
# Variants and versions
# ======================================================================================


class ResumeRead(Schema):
    """A named resume variant — configuration, not content.

    ``latest_version`` is not an ORM attribute (the model exposes an ordered ``versions``
    collection, which is lazily loaded); it defaults to ``None`` and is populated by the
    service layer when the caller asked for it.
    """

    id: uuid.UUID
    user_id: uuid.UUID
    name: str
    variant_label: str | None = Field(
        default=None,
        description="Short targeting label passed through as TailorRequest.variant_label.",
    )
    template: str = DEFAULT_RESUME_TEMPLATE
    is_default: bool = Field(
        default=False,
        description="Chosen when a tailoring request names no variant.",
    )
    config: dict[str, Any] = Field(
        default_factory=dict,
        description="Generation overrides: max_bullets, section order, tone.",
    )
    version_count: int = Field(
        default=0,
        description="Number of versions generated; populated by the service layer.",
    )
    latest_version: ResumeVersionRead | None = Field(
        default=None,
        description="Most recent version, when the caller requested it.",
    )
    created_at: datetime
    updated_at: datetime


class ResumeCreate(Schema):
    """Payload for creating a resume variant.

    Only ``name`` is required. Everything else falls back to the user's preferences and the
    packaged defaults, so a user can create a variant without understanding the template
    system first.
    """

    name: str = Field(min_length=1, description="Display name in the resume picker.")
    variant_label: str | None = None
    template: str = Field(
        default=DEFAULT_RESUME_TEMPLATE,
        description="TemplatePlugin used to render versions of this variant.",
    )
    is_default: bool = Field(
        default=False,
        description="Make this the variant chosen when a request names none.",
    )
    config: dict[str, Any] = Field(default_factory=dict)


class ResumeVersionRead(Schema):
    """One immutable generation of a resume, with full provenance.

    ``content_json`` is the permanent record and is always present. ``file_id`` and
    ``download_url`` are frequently ``None``: the rendered artifact is deleted after
    submission when ``settings.delete_temp_resume_after_submit`` is on, and the version can
    always be re-rendered from ``content_json``.
    """

    id: uuid.UUID
    resume_id: uuid.UUID
    application_id: uuid.UUID | None = None
    version_number: int = 1
    content_json: ResumeDocumentSchema = Field(
        default_factory=ResumeDocumentSchema,
        description="The structured resume; canonical and retained forever.",
    )
    render_format: str = DEFAULT_RENDER_FORMAT
    file_id: uuid.UUID | None = Field(
        default=None,
        description="Rendered artifact. None once cleanup has reclaimed the bytes.",
    )
    download_url: str | None = Field(
        default=None,
        description="Link to GET /resumes/versions/{id}/download; set by the API layer.",
    )
    fact_ids: list[str] = Field(
        default_factory=list,
        description="KnowledgeFact ids every bullet traces to.",
    )
    token_usage: dict[str, Any] = Field(default_factory=dict)
    reasoning: str | None = Field(
        default=None,
        description="Model's explanation of which facts it selected and why.",
    )
    bullet_count: int = Field(default=0, description="Number of facts drawn on.")
    has_artifact: bool = Field(
        default=False,
        description="Whether a rendered file is currently attached.",
    )
    deleted_at: datetime | None = None
    created_at: datetime
    updated_at: datetime


class ResumePreviewRequest(Schema):
    """Body of ``POST /resumes/preview`` — tailor a resume without applying to anything.

    This is the "show me what you would send" path. It runs the same
    :class:`app.ai.resume_engine.ResumeEngine` tailoring as a real application, including the
    anti-hallucination checks, but creates no :class:`~app.models.application.Application`
    and submits nothing.

    With ``posting_id`` omitted the engine produces a generic resume from the highest-impact
    facts, which is what the onboarding preview and the "master resume" view render.
    """

    posting_id: uuid.UUID | None = Field(
        default=None,
        description="Posting to tailor against; None produces an untargeted resume.",
    )
    resume_id: uuid.UUID | None = Field(
        default=None,
        description="Variant supplying template and config; None uses the default variant.",
    )
    template: str | None = Field(
        default=None,
        description="Override the variant's template for this preview only.",
    )
    variant_label: str | None = None
    max_bullets: int = Field(
        default=DEFAULT_TAILOR_BULLETS,
        ge=1,
        le=MAX_TAILOR_BULLETS,
        description="Bullet budget for the tailoring pass.",
    )
    render_format: RenderFormat = Field(
        default="pdf",
        description="Format to render the preview in.",
    )
    render: bool = Field(
        default=True,
        description="Render an artifact; False returns the structured document only.",
    )


# ``ResumeRead.latest_version`` forward-references ``ResumeVersionRead``, declared below it
# so that variants read before versions.
ResumeRead.model_rebuild()
