"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Creates all twenty-two tables of the ApplicantOS schema, hand-written rather than
autogenerated so that every constraint name, referential action and index is a deliberate
decision rather than whatever a diff happened to emit.

Design notes that matter when reading or extending this file:

**Portable column types, not literal ones.** The ``GUID`` / ``JSONType`` / ``EmbeddingType``
/ ``UTCDateTime`` decorators from :mod:`app.database.types` are imported and used directly,
exactly as the models declare them. Substituting ``sa.String(36)`` for ``GUID`` would create
a text primary key on PostgreSQL where the models expect a native ``uuid``, and the mismatch
would only surface as an autogenerate diff — or a cast error — much later.

**Enums are VARCHAR, not native types.** Every enum column in the models is declared
``sa.Enum(..., native_enum=False)`` with ``create_constraint`` left at its default of
``False``, which compiles to a plain ``VARCHAR(n)`` on every backend. This migration spells
that out as :class:`sqlalchemy.String` with the same width, so SQLite works and so adding an
enum member never requires a PostgreSQL type migration. The widths are the longest current
*value* of each enum — that is what SQLAlchemy computes when no explicit length is given —
and they are named as constants below rather than inlined.

**The applications ⇄ documents cycle.** ``applications.resume_version_id`` and
``applications.cover_letter_id`` point at tables that point back at ``applications``, so no
single ordering of ``CREATE TABLE`` statements can satisfy both. The models declare those two
foreign keys ``use_alter=True``, and this migration resolves the cycle the same way
SQLAlchemy's own ``create_all`` does — differently per backend, because the backends differ:

* On PostgreSQL the two constraints are added by ``ALTER TABLE`` once all three tables exist.
* On SQLite, which has no ``ALTER TABLE ... ADD CONSTRAINT``, they are declared inline in
  ``CREATE TABLE applications``. SQLite resolves foreign key targets lazily, so referencing a
  table that does not exist yet is legal.

Either way the constraints end up present on both backends, and the schema this migration
produces is byte-identical to ``Base.metadata.create_all``.

**Referential actions are load-bearing.** ``applications.posting_id`` is ``RESTRICT``, not
``CASCADE``: deleting an applied-to posting must fail loudly rather than erase the evidence
behind "never apply twice". ``knowledge_facts.source_document_id`` is ``SET NULL``, so a
verified fact outlives the document it was extracted from. Company references are
``SET NULL`` everywhere, so merging employer records never destroys application history.

**pgvector.** The extension is created only on PostgreSQL, and only when the ``pgvector``
Python package is importable — that package's presence is precisely the condition under
which :class:`~app.database.types.EmbeddingType` renders a ``vector(n)`` column rather than
falling back to JSON. Creating it unconditionally would fail on a PostgreSQL server that
does not ship the extension, for a schema that would not have used it.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Final

import sqlalchemy as sa

from alembic import op
from app.database.types import (
    GUID,
    POSTGRES_DIALECT_NAMES,
    EmbeddingType,
    JSONType,
    UTCDateTime,
)

#: Identifier of this revision.
revision: str = "0001"

#: Revision this one builds on; ``None`` because this is the first.
down_revision: str | None = None

#: Branch labels, unused: this project keeps one linear history.
branch_labels: str | Sequence[str] | None = None

#: Dependencies on other version directories, unused.
depends_on: str | Sequence[str] | None = None


# ======================================================================================
# Column widths
#
# Every width below mirrors a module constant in app/models/. Enum widths are the longest
# member *value*, which is what sa.Enum(native_enum=False) computes when given no explicit
# length; the two knowledge/profile helpers pass length=64 explicitly, hence ENUM_WIDE.
# ======================================================================================

#: Width of the VARCHAR backing enums declared through the ``_enum_column_type`` helpers in
#: ``app/models/profile.py`` and ``app/models/knowledge.py`` (explicit ``length=64``).
ENUM_WIDE: Final[int] = 64

#: ``ATSProviderName`` — longest value ``"greenhouse"``.
ENUM_PROVIDER: Final[int] = 10

#: ``PostingStatus`` — longest value ``"needs_review"``.
ENUM_POSTING_STATUS: Final[int] = 12

#: ``WorkArrangement`` — longest value ``"unknown"``.
ENUM_WORK_ARRANGEMENT: Final[int] = 7

#: ``EmploymentType`` — longest value ``"internship"``.
ENUM_EMPLOYMENT_TYPE: Final[int] = 10

#: ``ApplicationStatus`` — longest value ``"needs_review"``.
ENUM_APPLICATION_STATUS: Final[int] = 12

#: ``ReviewReason`` — longest value ``"verification_failed"``.
ENUM_REVIEW_REASON: Final[int] = 19

#: ``SessionStatus`` — longest values ``"completed"`` / ``"cancelled"``.
ENUM_SESSION_STATUS: Final[int] = 9

#: ``CheckpointStatus`` — longest value ``"compensated"``.
ENUM_CHECKPOINT_STATUS: Final[int] = 11

#: ``DocumentKind`` — longest values ``"tailored_resume"`` / ``"source_document"``.
ENUM_DOCUMENT_KIND: Final[int] = 15

#: Hex width of a SHA-256 digest, used by every ``content_hash`` / ``sha256`` column.
SHA256_HEX: Final[int] = 64

#: RFC 5321 maximum email length (64-octet local part + ``@`` + 255-octet domain).
EMAIL_MAX: Final[int] = 320

#: Generous ceiling for a human name.
FULL_NAME_MAX: Final[int] = 255

#: Short free-text answers: pronouns, citizenship, clearance, EEO values.
SHORT_TEXT_MAX: Final[int] = 255

#: Phone numbers, stored exactly as typed (separators, extensions, country prefixes).
PHONE_MAX: Final[int] = 64

#: ISO 4217 currency codes.
CURRENCY_LEN: Final[int] = 3

#: Free-text availability ("Immediately", "2026-06-01", "after May graduation").
AVAILABILITY_MAX: Final[int] = 64

#: Company display name and its normalisation key.
COMPANY_NAME_MAX: Final[int] = 255

#: Registrable domain length per RFC 1035.
DOMAIN_MAX: Final[int] = 253

#: Free-text industry label.
INDUSTRY_MAX: Final[int] = 128

#: Headcount band label such as ``"1001-5000"``.
SIZE_BUCKET_MAX: Final[int] = 32

#: URLs, absolute filesystem paths, and ``repo#path`` composites in the knowledge engine.
URI_MAX: Final[int] = 2048

#: Human-facing titles and labels in the knowledge engine.
TITLE_MAX: Final[int] = 512

#: Entity display names and their normalised form.
ENTITY_NAME_MAX: Final[int] = 512

#: Short free-text attributes on a fact: organization, role, location.
ATTRIBUTE_MAX: Final[int] = 255

#: Dates on facts, stored as the source wrote them ("2024-06", "Summer 2023", "Present").
DATE_TEXT_MAX: Final[int] = 64

#: HTTP entity tags, bounded by convention rather than specification.
ETAG_MAX: Final[int] = 255

#: Provider-native posting identifier.
EXTERNAL_ID_MAX: Final[int] = 255

#: Posting title.
POSTING_TITLE_MAX: Final[int] = 512

#: Advertised location string.
POSTING_LOCATION_MAX: Final[int] = 255

#: Cross-provider dedupe key (a composite of normalised company/title/location).
DEDUPE_KEY_MAX: Final[int] = 255

#: Scoring verdict label (``"apply"`` / ``"review"`` / ``"skip"``).
VERDICT_MAX: Final[int] = 32

#: Identifier of the model that wrote a score rationale.
MODEL_NAME_MAX: Final[int] = 128

#: Resume variant display name and targeting label.
RESUME_NAME_MAX: Final[int] = 120

#: Template plugin name (``modern``, ``classic``, ``ats_plain``, …).
RESUME_TEMPLATE_MAX: Final[int] = 64

#: Render format token (``pdf``, ``docx``, ``md``, ``html``).
RENDER_FORMAT_MAX: Final[int] = 16

#: Cover letter tone label.
TONE_MAX: Final[int] = 32

#: Employer-issued confirmation reference and the ATS's own application identifier.
CONFIRMATION_ID_MAX: Final[int] = 255

#: Application event kind token (``prepared``, ``submitted``, ``needs_review``).
EVENT_KIND_MAX: Final[int] = 64

#: Run session trigger label (``manual``, ``schedule``, ``api``).
SESSION_TRIGGER_MAX: Final[int] = 32

#: Checkpoint idempotency key — a structured string, not a digest.
CHECKPOINT_KEY_MAX: Final[int] = 255

#: Checkpoint owner group label and step name.
CHECKPOINT_LABEL_MAX: Final[int] = 128

#: Uploaded filename, MIME type, storage key, and backend name.
FILENAME_MAX: Final[int] = 255
CONTENT_TYPE_MAX: Final[int] = 255
STORAGE_KEY_MAX: Final[int] = 1024
STORAGE_BACKEND_MAX: Final[int] = 32

#: Log level name, dotted event name, logger name, correlation identifier.
LOG_LEVEL_MAX: Final[int] = 16
LOG_EVENT_MAX: Final[int] = 255
LOGGER_NAME_MAX: Final[int] = 255
CORRELATION_ID_MAX: Final[int] = 64

#: Cache key and namespace.
CACHE_KEY_MAX: Final[int] = 255
CACHE_NAMESPACE_MAX: Final[int] = 64


# ======================================================================================
# Server defaults
#
# Only the columns whose models declare ``server_default=`` appear here. Columns with a
# Python-side ``default=`` only (JSON containers, most booleans, enum defaults) deliberately
# get no server default: the ORM supplies the value, and inventing one here would make the
# migration disagree with the models the first time autogenerate is run.
# ======================================================================================

#: Zero, for every counter column that declares a server default.
ZERO: Final[str] = "0"

#: True, for ``checkpoints.resumable``.
TRUE: Final[str] = "1"

#: Default resume template, mirroring ``settings.resume_template``.
DEFAULT_TEMPLATE: Final[str] = "modern"

#: Default render format for a resume version.
DEFAULT_RENDER_FORMAT: Final[str] = "pdf"

#: Default cover letter tone.
DEFAULT_TONE: Final[str] = "professional"

#: Default storage backend, mirroring ``settings.storage_backend``.
DEFAULT_STORAGE_BACKEND: Final[str] = "local"

#: Default run session trigger.
DEFAULT_SESSION_TRIGGER: Final[str] = "manual"


# ======================================================================================
# Shared column groups
# ======================================================================================


def _id_column() -> sa.Column:
    """Return the UUID primary key column shared by every table.

    Values are generated in Python (``uuid.uuid4``) rather than by the database, so an
    object has a stable identity before it is flushed — which is what lets the pipeline
    build a whole object graph and write it in one transaction.
    """
    return sa.Column("id", GUID(), nullable=False)


def _user_id_column(*, nullable: bool = False) -> sa.Column:
    """Return the owning-user foreign key column.

    Args:
        nullable: ``True`` only for ``uploaded_files``, where system-owned artifacts have no
            owning user.
    """
    return sa.Column("user_id", GUID(), nullable=nullable)


def _timestamp_columns() -> tuple[sa.Column, sa.Column]:
    """Return the ``created_at`` / ``updated_at`` audit columns.

    Both carry a server default as well as a Python-side one: the Python default keeps the
    value on the in-memory object immediately, the server default protects rows written by
    a migration or by raw SQL. ``updated_at`` has no ``server_onupdate`` because there is no
    portable spelling of one across PostgreSQL and SQLite; SQLAlchemy's ``onupdate`` hook
    maintains it instead.
    """
    return (
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UTCDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )


def _deleted_at_column() -> sa.Column:
    """Return the soft-deletion stamp used by ``uploaded_files`` and ``resume_versions``.

    Rows are retired by stamping a timestamp rather than being removed, so history stays
    auditable and foreign keys stay intact (golden rule #6).
    """
    return sa.Column("deleted_at", UTCDateTime(), nullable=True)


def _user_fk(table: str) -> sa.ForeignKeyConstraint:
    """Return the ``user_id -> users.id`` foreign key for *table*.

    ``CASCADE``: deleting a user must not leave orphaned applications, facts, or documents
    behind. On SQLite this is only honoured because :mod:`app.database.session` issues
    ``PRAGMA foreign_keys=ON`` on every connection.

    Args:
        table: The referencing table's name, used to build the constraint name.
    """
    return sa.ForeignKeyConstraint(
        ["user_id"],
        ["users.id"],
        name=f"fk_{table}_user_id_users",
        ondelete="CASCADE",
    )


# ======================================================================================
# pgvector
# ======================================================================================


def _needs_vector_extension(bind: sa.engine.Connection) -> bool:
    """Return whether ``CREATE EXTENSION vector`` should run for this connection.

    Both conditions must hold, and they are different questions:

    * The dialect must be PostgreSQL — SQLite has no extensions of this kind.
    * The ``pgvector`` **Python package** must be importable, because that is exactly the
      condition under which :class:`~app.database.types.EmbeddingType` renders a
      ``vector(n)`` column. Without it, embedding columns are plain JSON and the server-side
      extension is irrelevant.

    Checking only the dialect would fail the migration on a PostgreSQL server that does not
    ship the extension, for a schema that would not have used it.

    Args:
        bind: The connection migrations are running on.

    Returns:
        ``True`` when the extension is both meaningful and required.
    """
    if bind.dialect.name not in POSTGRES_DIALECT_NAMES:
        return False
    try:
        import pgvector.sqlalchemy  # noqa: F401  - presence check only
    except ImportError:
        return False
    return True


def upgrade() -> None:
    """Create the entire ApplicantOS schema.

    Tables are created in dependency order, so every foreign key target already exists —
    with the single, documented exception of the ``applications`` ⇄ documents cycle, whose
    two pointers are added by ``ALTER`` at the end.
    """
    bind = op.get_bind()

    if _needs_vector_extension(bind):
        # Idempotent, and required before any vector(n) column is created.
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    _create_users()
    _create_companies()
    _create_cache_entries()
    _create_log_entries()
    _create_user_profiles()
    _create_uploaded_files()
    _create_run_sessions()
    _create_checkpoints()
    _create_knowledge_sources()
    _create_knowledge_documents()
    _create_knowledge_chunks()
    _create_knowledge_entities()
    _create_knowledge_edges()
    _create_knowledge_facts()
    _create_memory_entries()
    _create_job_postings()
    _create_job_scores()
    _create_resumes()
    _create_applications(bind)
    _create_resume_versions()
    _create_cover_letters()
    _create_application_events()

    _create_deferred_application_foreign_keys(bind)


def downgrade() -> None:
    """Drop the entire schema, in exact reverse dependency order.

    ``DROP TABLE`` removes a table's own indexes and constraints on both backends, so those
    are not dropped individually — only the ``applications`` ⇄ documents cycle needs
    unpicking first, because ``applications`` outlives the two tables it points at.

    The ``vector`` extension is deliberately *not* dropped: it is database-scoped shared
    state that another schema in the same database may be using, and re-creating it is
    cheap while losing someone else's vector columns is not.
    """
    bind = op.get_bind()

    _drop_deferred_application_foreign_keys(bind)

    op.drop_table("application_events")
    op.drop_table("cover_letters")
    op.drop_table("resume_versions")
    op.drop_table("applications")
    op.drop_table("resumes")
    op.drop_table("job_scores")
    op.drop_table("job_postings")
    op.drop_table("memory_entries")
    op.drop_table("knowledge_facts")
    op.drop_table("knowledge_edges")
    op.drop_table("knowledge_entities")
    op.drop_table("knowledge_chunks")
    op.drop_table("knowledge_documents")
    op.drop_table("knowledge_sources")
    op.drop_table("checkpoints")
    op.drop_table("run_sessions")
    op.drop_table("uploaded_files")
    op.drop_table("user_profiles")
    op.drop_table("log_entries")
    op.drop_table("cache_entries")
    op.drop_table("companies")
    op.drop_table("users")


# ======================================================================================
# Identity and profile
# ======================================================================================


def _create_users() -> None:
    """Create ``users`` — the root of every ownership chain in the schema."""
    op.create_table(
        "users",
        _id_column(),
        sa.Column("email", sa.String(EMAIL_MAX), nullable=False),
        sa.Column("full_name", sa.String(FULL_NAME_MAX), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("onboarded_at", UTCDateTime(), nullable=True),
        sa.Column("preferences", JSONType(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    # Unique *and* indexed: a case-varying duplicate would create a second account with a
    # second knowledge graph, so the constraint is the guarantee and the index serves login.
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_created_at", "users", ["created_at"], unique=False)


def _create_user_profiles() -> None:
    """Create ``user_profiles`` — structured answers to every question a form asks."""
    op.create_table(
        "user_profiles",
        _id_column(),
        _user_id_column(),
        # -- contact and identity ----------------------------------------------------
        sa.Column("phone", sa.String(PHONE_MAX), nullable=True),
        sa.Column("pronouns", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("location", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("address", JSONType(), nullable=False),
        sa.Column("links", JSONType(), nullable=False),
        # -- work authorisation ------------------------------------------------------
        sa.Column("citizenship", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("work_authorization", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("requires_sponsorship", sa.Boolean(), nullable=False),
        # -- EEO / self-identification: nullable, never inferred, always declinable ---
        sa.Column("veteran_status", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("gender", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("race_ethnicity", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("disability_status", sa.String(SHORT_TEXT_MAX), nullable=True),
        sa.Column("clearance", sa.String(SHORT_TEXT_MAX), nullable=True),
        # -- compensation and location -----------------------------------------------
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(CURRENCY_LEN), nullable=False),
        sa.Column("remote_preference", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("willing_to_relocate", sa.Boolean(), nullable=False),
        sa.Column("relocation_targets", JSONType(), nullable=False),
        # -- targeting ----------------------------------------------------------------
        sa.Column("desired_roles", JSONType(), nullable=False),
        sa.Column("desired_industries", JSONType(), nullable=False),
        sa.Column("excluded_companies", JSONType(), nullable=False),
        sa.Column("excluded_industries", JSONType(), nullable=False),
        # -- education, availability, overflow ----------------------------------------
        sa.Column("education", JSONType(), nullable=False),
        sa.Column("start_date_availability", sa.String(AVAILABILITY_MAX), nullable=True),
        sa.Column("notice_period_weeks", sa.Integer(), nullable=True),
        sa.Column("extra", JSONType(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_user_profiles"),
        _user_fk("user_profiles"),
        # One profile per user, enforced separately from the primary key so the profile
        # keeps its own identity and can be replaced wholesale during onboarding.
        sa.UniqueConstraint("user_id", name="uq_user_profiles_user_id"),
    )
    op.create_index("ix_user_profiles_user_id", "user_profiles", ["user_id"], unique=False)
    op.create_index(
        "ix_user_profiles_created_at", "user_profiles", ["created_at"], unique=False
    )


# ======================================================================================
# Reference data and infrastructure tables
# ======================================================================================


def _create_companies() -> None:
    """Create ``companies`` — the shared employer dimension.

    Reference data: no cascade points outward from this table. Both referencing columns
    (``job_postings.company_id``, ``applications.company_id``) are ``SET NULL``, so purging
    or merging a company record never destroys postings or application history.
    """
    op.create_table(
        "companies",
        _id_column(),
        sa.Column("name", sa.String(COMPANY_NAME_MAX), nullable=False),
        sa.Column("normalized_name", sa.String(COMPANY_NAME_MAX), nullable=False),
        sa.Column("domain", sa.String(DOMAIN_MAX), nullable=True),
        sa.Column("industry", sa.String(INDUSTRY_MAX), nullable=True),
        sa.Column("size_bucket", sa.String(SIZE_BUCKET_MAX), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column(
            "is_defense", sa.Boolean(), server_default=ZERO, nullable=False
        ),
        sa.Column(
            "is_startup", sa.Boolean(), server_default=ZERO, nullable=False
        ),
        sa.Column("metadata_json", JSONType(), nullable=False),
        sa.Column("enriched_at", UTCDateTime(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_companies"),
    )
    # The unique index on the normalised name is what stops "Acme, Inc.", "ACME Inc" and
    # "Acme Incorporated" from fragmenting the block list and the analytics.
    op.create_index(
        "ix_companies_normalized_name", "companies", ["normalized_name"], unique=True
    )
    op.create_index("ix_companies_domain", "companies", ["domain"], unique=False)
    op.create_index("ix_companies_created_at", "companies", ["created_at"], unique=False)


def _create_cache_entries() -> None:
    """Create ``cache_entries`` — the durable tier of :mod:`app.cache`."""
    op.create_table(
        "cache_entries",
        _id_column(),
        sa.Column("key", sa.String(CACHE_KEY_MAX), nullable=False),
        sa.Column("namespace", sa.String(CACHE_NAMESPACE_MAX), nullable=False),
        sa.Column("value", JSONType(), nullable=True),
        sa.Column("content_hash", sa.String(SHA256_HEX), nullable=True),
        sa.Column("hits", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("expires_at", UTCDateTime(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cache_entries"),
    )
    # Uniqueness on the content-addressed key makes a write an upsert and makes a
    # concurrent double-compute converge on one row.
    op.create_index("ix_cache_entries_key", "cache_entries", ["key"], unique=True)
    op.create_index(
        "ix_cache_entries_created_at", "cache_entries", ["created_at"], unique=False
    )
    # The only two maintenance shapes: namespace invalidation, and the expiry sweep.
    op.create_index(
        "ix_cache_entries_namespace_expires_at",
        "cache_entries",
        ["namespace", "expires_at"],
        unique=False,
    )


def _create_log_entries() -> None:
    """Create ``log_entries`` — the queryable tail of the structlog stream.

    ``session_id``, ``application_id`` and ``posting_id`` are correlation identifiers, **not**
    foreign keys: a log line must be writable for an entity whose transaction rolled back,
    cascading deletes would destroy the audit trail of whatever was deleted, and this is the
    highest-write table in the schema.
    """
    op.create_table(
        "log_entries",
        _id_column(),
        sa.Column("level", sa.String(LOG_LEVEL_MAX), nullable=False),
        sa.Column("event", sa.String(LOG_EVENT_MAX), nullable=False),
        sa.Column("logger", sa.String(LOGGER_NAME_MAX), nullable=True),
        sa.Column("correlation_id", sa.String(CORRELATION_ID_MAX), nullable=True),
        sa.Column("session_id", GUID(), nullable=True),
        sa.Column("application_id", GUID(), nullable=True),
        sa.Column("posting_id", GUID(), nullable=True),
        sa.Column("payload", JSONType(), nullable=False),
        sa.Column("at", UTCDateTime(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_log_entries"),
    )
    op.create_index("ix_log_entries_level", "log_entries", ["level"], unique=False)
    op.create_index(
        "ix_log_entries_correlation_id", "log_entries", ["correlation_id"], unique=False
    )
    op.create_index("ix_log_entries_at", "log_entries", ["at"], unique=False)
    op.create_index(
        "ix_log_entries_created_at", "log_entries", ["created_at"], unique=False
    )
    # The application detail view's timeline: one application's lines, in order.
    op.create_index(
        "ix_log_entries_application_id_at",
        "log_entries",
        ["application_id", "at"],
        unique=False,
    )


def _create_uploaded_files() -> None:
    """Create ``uploaded_files`` — the metadata index over the blob store.

    ``user_id`` is nullable here rather than inherited from the owning-user mixin, because
    some artifacts belong to the system rather than to a person.
    """
    op.create_table(
        "uploaded_files",
        _id_column(),
        _user_id_column(nullable=True),
        sa.Column("kind", sa.String(ENUM_DOCUMENT_KIND), nullable=False),
        sa.Column("filename", sa.String(FILENAME_MAX), nullable=False),
        sa.Column("content_type", sa.String(CONTENT_TYPE_MAX), nullable=True),
        sa.Column("size_bytes", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("storage_key", sa.String(STORAGE_KEY_MAX), nullable=False),
        sa.Column("sha256", sa.String(SHA256_HEX), nullable=True),
        sa.Column(
            "backend",
            sa.String(STORAGE_BACKEND_MAX),
            server_default=DEFAULT_STORAGE_BACKEND,
            nullable=False,
        ),
        sa.Column("expires_at", UTCDateTime(), nullable=True),
        *_timestamp_columns(),
        _deleted_at_column(),
        sa.PrimaryKeyConstraint("id", name="pk_uploaded_files"),
        _user_fk("uploaded_files"),
    )
    op.create_index(
        "ix_uploaded_files_user_id", "uploaded_files", ["user_id"], unique=False
    )
    op.create_index(
        "ix_uploaded_files_storage_key", "uploaded_files", ["storage_key"], unique=False
    )
    # Content address: the storage layer deduplicates and cache-keys on it.
    op.create_index("ix_uploaded_files_sha256", "uploaded_files", ["sha256"], unique=False)
    op.create_index(
        "ix_uploaded_files_expires_at", "uploaded_files", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_uploaded_files_created_at", "uploaded_files", ["created_at"], unique=False
    )
    op.create_index(
        "ix_uploaded_files_deleted_at", "uploaded_files", ["deleted_at"], unique=False
    )
    # Maintenance sweeps: "every live screenshot", "every retired tailored resume".
    op.create_index(
        "ix_uploaded_files_kind_deleted_at",
        "uploaded_files",
        ["kind", "deleted_at"],
        unique=False,
    )


# ======================================================================================
# Runtime: sessions and checkpoints
# ======================================================================================


def _create_run_sessions() -> None:
    """Create ``run_sessions`` — one automation run and its rollup counters."""
    op.create_table(
        "run_sessions",
        _id_column(),
        _user_id_column(),
        sa.Column("status", sa.String(ENUM_SESSION_STATUS), nullable=False),
        sa.Column("started_at", UTCDateTime(), nullable=False),
        sa.Column("ended_at", UTCDateTime(), nullable=True),
        # -- rollup counters ----------------------------------------------------------
        sa.Column("jobs_found", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("jobs_qualified", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("resumes_generated", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column(
            "applications_completed", sa.Integer(), server_default=ZERO, nullable=False
        ),
        sa.Column("manual_review", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("failures", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("avg_application_seconds", sa.Float(), nullable=True),
        # -- provenance ----------------------------------------------------------------
        sa.Column("token_usage", JSONType(), nullable=False),
        sa.Column("config_snapshot", JSONType(), nullable=False),
        sa.Column(
            "trigger",
            sa.String(SESSION_TRIGGER_MAX),
            server_default=DEFAULT_SESSION_TRIGGER,
            nullable=False,
        ),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_run_sessions"),
        _user_fk("run_sessions"),
    )
    op.create_index("ix_run_sessions_user_id", "run_sessions", ["user_id"], unique=False)
    op.create_index("ix_run_sessions_status", "run_sessions", ["status"], unique=False)
    op.create_index(
        "ix_run_sessions_started_at", "run_sessions", ["started_at"], unique=False
    )
    op.create_index(
        "ix_run_sessions_created_at", "run_sessions", ["created_at"], unique=False
    )


def _create_checkpoints() -> None:
    """Create ``checkpoints`` — the rows that make "everything is resumable" true.

    ``session_id`` is ``SET NULL``: pruning old sessions is routine maintenance and must
    never delete state a crash-recovery pass still needs.
    """
    op.create_table(
        "checkpoints",
        _id_column(),
        sa.Column("session_id", GUID(), nullable=True),
        sa.Column("key", sa.String(CHECKPOINT_KEY_MAX), nullable=False),
        sa.Column("owner", sa.String(CHECKPOINT_LABEL_MAX), nullable=False),
        sa.Column("step", sa.String(CHECKPOINT_LABEL_MAX), nullable=False),
        sa.Column("status", sa.String(ENUM_CHECKPOINT_STATUS), nullable=False),
        sa.Column("state", JSONType(), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("resumable", sa.Boolean(), server_default=TRUE, nullable=False),
        sa.Column("expires_at", UTCDateTime(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_checkpoints"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["run_sessions.id"],
            name="fk_checkpoints_session_id_run_sessions",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_checkpoints_session_id", "checkpoints", ["session_id"], unique=False)
    # Uniqueness on the caller-chosen key is the whole mechanism: two workers racing to
    # start the same step collide here, and the loser reads the winner's row.
    op.create_index("ix_checkpoints_key", "checkpoints", ["key"], unique=True)
    op.create_index("ix_checkpoints_expires_at", "checkpoints", ["expires_at"], unique=False)
    op.create_index("ix_checkpoints_created_at", "checkpoints", ["created_at"], unique=False)
    # Crash recovery scans one operation's steps by status.
    op.create_index(
        "ix_checkpoints_owner_status", "checkpoints", ["owner", "status"], unique=False
    )


# ======================================================================================
# Knowledge engine
# ======================================================================================


def _create_knowledge_sources() -> None:
    """Create ``knowledge_sources`` — what the user pointed the indexer at."""
    op.create_table(
        "knowledge_sources",
        _id_column(),
        _user_id_column(),
        sa.Column("kind", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("uri", sa.String(URI_MAX), nullable=False),
        sa.Column("label", sa.String(TITLE_MAX), nullable=True),
        sa.Column("config", JSONType(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("index_status", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("last_indexed_at", UTCDateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("etag", sa.String(ETAG_MAX), nullable=True),
        sa.Column("content_hash", sa.String(SHA256_HEX), nullable=True),
        sa.Column("auto_refresh", sa.Boolean(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_sources"),
        _user_fk("knowledge_sources"),
        # The same account cannot be registered twice, and the same path cannot be both a
        # project_folder and a readme by accident.
        sa.UniqueConstraint(
            "user_id", "kind", "uri", name="uq_knowledge_sources_user_id_kind_uri"
        ),
    )
    op.create_index(
        "ix_knowledge_sources_user_id", "knowledge_sources", ["user_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_sources_kind", "knowledge_sources", ["kind"], unique=False
    )
    op.create_index(
        "ix_knowledge_sources_index_status",
        "knowledge_sources",
        ["index_status"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_sources_created_at",
        "knowledge_sources",
        ["created_at"],
        unique=False,
    )


def _create_knowledge_documents() -> None:
    """Create ``knowledge_documents`` — one extracted text artifact each."""
    op.create_table(
        "knowledge_documents",
        _id_column(),
        _user_id_column(),
        sa.Column("source_id", GUID(), nullable=False),
        sa.Column("kind", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("uri", sa.String(URI_MAX), nullable=False),
        sa.Column("title", sa.String(TITLE_MAX), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(SHA256_HEX), nullable=False),
        sa.Column("metadata_json", JSONType(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("indexed_at", UTCDateTime(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_documents"),
        _user_fk("knowledge_documents"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge_sources.id"],
            name="fk_knowledge_documents_source_id_knowledge_sources",
            ondelete="CASCADE",
        ),
        # Re-indexing updates the existing row rather than accumulating duplicates.
        sa.UniqueConstraint(
            "source_id", "uri", name="uq_knowledge_documents_source_id_uri"
        ),
    )
    op.create_index(
        "ix_knowledge_documents_user_id", "knowledge_documents", ["user_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_documents_source_id",
        "knowledge_documents",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_documents_kind", "knowledge_documents", ["kind"], unique=False
    )
    # "Did this document change?" is the indexer's first question about every re-extraction;
    # answering it from an index avoids the most expensive step in the whole pipeline.
    op.create_index(
        "ix_knowledge_documents_content_hash",
        "knowledge_documents",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_documents_created_at",
        "knowledge_documents",
        ["created_at"],
        unique=False,
    )


def _create_knowledge_chunks() -> None:
    """Create ``knowledge_chunks`` — the unit of semantic retrieval.

    The only table with no ``user_id``: chunks are reachable exclusively through their
    document, which is user-owned, and denormalising ownership here would double the write
    volume of the hottest table in the system for no query benefit.
    """
    op.create_table(
        "knowledge_chunks",
        _id_column(),
        sa.Column("document_id", GUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", EmbeddingType(), nullable=True),
        sa.Column("metadata_json", JSONType(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_chunks"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name="fk_knowledge_chunks_document_id_knowledge_documents",
            ondelete="CASCADE",
        ),
        # Re-chunking is an idempotent upsert.
        sa.UniqueConstraint(
            "document_id", "ordinal", name="uq_knowledge_chunks_document_id_ordinal"
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_document_id",
        "knowledge_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_chunks_created_at", "knowledge_chunks", ["created_at"], unique=False
    )


def _create_knowledge_entities() -> None:
    """Create ``knowledge_entities`` — the nodes of the user's knowledge graph."""
    op.create_table(
        "knowledge_entities",
        _id_column(),
        _user_id_column(),
        sa.Column("kind", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("name", sa.String(ENTITY_NAME_MAX), nullable=False),
        sa.Column("normalized_name", sa.String(ENTITY_NAME_MAX), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("attributes", JSONType(), nullable=False),
        sa.Column("aliases", JSONType(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", UTCDateTime(), nullable=False),
        sa.Column("embedding", EmbeddingType(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_entities"),
        _user_fk("knowledge_entities"),
        # "Node.js", "NodeJS" and "node.js" are one node; "C", "C++" and "C#" are three.
        sa.UniqueConstraint(
            "user_id",
            "kind",
            "normalized_name",
            name="uq_knowledge_entities_user_id_kind_normalized_name",
        ),
    )
    op.create_index(
        "ix_knowledge_entities_user_id", "knowledge_entities", ["user_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_entities_kind", "knowledge_entities", ["kind"], unique=False
    )
    op.create_index(
        "ix_knowledge_entities_normalized_name",
        "knowledge_entities",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_entities_created_at",
        "knowledge_entities",
        ["created_at"],
        unique=False,
    )


def _create_knowledge_edges() -> None:
    """Create ``knowledge_edges`` — typed, weighted relationships between entities.

    Both endpoints reference the same table, which makes this a self-referential
    association; the models name ``foreign_keys`` explicitly on every relationship for the
    same reason.
    """
    op.create_table(
        "knowledge_edges",
        _id_column(),
        _user_id_column(),
        sa.Column("source_entity_id", GUID(), nullable=False),
        sa.Column("target_entity_id", GUID(), nullable=False),
        sa.Column("relation", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("evidence", JSONType(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_edges"),
        _user_fk("knowledge_edges"),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["knowledge_entities.id"],
            name="fk_knowledge_edges_source_entity_id_knowledge_entities",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["knowledge_entities.id"],
            name="fk_knowledge_edges_target_entity_id_knowledge_entities",
            ondelete="CASCADE",
        ),
        # Repeated observations strengthen one row rather than multiplying rows.
        sa.UniqueConstraint(
            "source_entity_id",
            "target_entity_id",
            "relation",
            name="uq_knowledge_edges_source_entity_id_target_entity_id_relation",
        ),
    )
    op.create_index(
        "ix_knowledge_edges_user_id", "knowledge_edges", ["user_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_edges_source_entity_id",
        "knowledge_edges",
        ["source_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_edges_target_entity_id",
        "knowledge_edges",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_edges_relation", "knowledge_edges", ["relation"], unique=False
    )
    op.create_index(
        "ix_knowledge_edges_created_at", "knowledge_edges", ["created_at"], unique=False
    )


def _create_knowledge_facts() -> None:
    """Create ``knowledge_facts`` — one atomic, source-attributed claim per row.

    Provenance is a foreign key, not a comment — and both provenance pointers are
    ``SET NULL`` rather than ``CASCADE``. Re-indexing churns documents; a verified fact must
    outlive the document it was first seen in, losing only its pointer, never itself.
    """
    op.create_table(
        "knowledge_facts",
        _id_column(),
        _user_id_column(),
        sa.Column("kind", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("organization", sa.String(ATTRIBUTE_MAX), nullable=True),
        sa.Column("role", sa.String(ATTRIBUTE_MAX), nullable=True),
        sa.Column("location", sa.String(ATTRIBUTE_MAX), nullable=True),
        sa.Column("date_start", sa.String(DATE_TEXT_MAX), nullable=True),
        sa.Column("date_end", sa.String(DATE_TEXT_MAX), nullable=True),
        sa.Column("skills", JSONType(), nullable=False),
        sa.Column("technologies", JSONType(), nullable=False),
        sa.Column("metrics", JSONType(), nullable=False),
        sa.Column("impact_score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("embedding", EmbeddingType(), nullable=True),
        sa.Column("source_document_id", GUID(), nullable=True),
        sa.Column("entity_id", GUID(), nullable=True),
        sa.Column("user_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.String(SHA256_HEX), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_facts"),
        _user_fk("knowledge_facts"),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["knowledge_documents.id"],
            name="fk_knowledge_facts_source_document_id_knowledge_documents",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["knowledge_entities.id"],
            name="fk_knowledge_facts_entity_id_knowledge_entities",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_knowledge_facts_user_id", "knowledge_facts", ["user_id"], unique=False
    )
    op.create_index("ix_knowledge_facts_kind", "knowledge_facts", ["kind"], unique=False)
    op.create_index(
        "ix_knowledge_facts_source_document_id",
        "knowledge_facts",
        ["source_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_facts_entity_id", "knowledge_facts", ["entity_id"], unique=False
    )
    # Deduplication key: re-indexing an unchanged source produces the same digests and
    # updates rows in place instead of inserting near-duplicates.
    op.create_index(
        "ix_knowledge_facts_content_hash",
        "knowledge_facts",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_facts_created_at", "knowledge_facts", ["created_at"], unique=False
    )
    # "Give me this user's live facts" — the hottest read in the application, run on every
    # single resume tailoring pass.
    op.create_index(
        "ix_knowledge_facts_user_id_is_active",
        "knowledge_facts",
        ["user_id", "is_active"],
        unique=False,
    )


def _create_memory_entries() -> None:
    """Create ``memory_entries`` — corrections, outcomes, feedback, notes."""
    op.create_table(
        "memory_entries",
        _id_column(),
        _user_id_column(),
        sa.Column("kind", sa.String(ENUM_WIDE), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("context", JSONType(), nullable=False),
        sa.Column("embedding", EmbeddingType(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("expires_at", UTCDateTime(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_memory_entries"),
        _user_fk("memory_entries"),
    )
    op.create_index(
        "ix_memory_entries_user_id", "memory_entries", ["user_id"], unique=False
    )
    op.create_index("ix_memory_entries_kind", "memory_entries", ["kind"], unique=False)
    op.create_index(
        "ix_memory_entries_expires_at", "memory_entries", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_memory_entries_created_at", "memory_entries", ["created_at"], unique=False
    )


# ======================================================================================
# Postings and scoring
# ======================================================================================


def _create_job_postings() -> None:
    """Create ``job_postings`` — the entry point of the whole pipeline.

    Two independent unique constraints: ``(provider, external_id)`` makes re-polling a
    provider idempotent, and ``dedupe_key`` is the *cross-provider* guarantee that one role
    syndicated to three boards is one row. ``dedupe_key`` is nullable so a posting can exist
    between ingestion and dedupe — SQL treats NULLs as distinct, so any number of
    not-yet-deduped rows coexist.
    """
    op.create_table(
        "job_postings",
        _id_column(),
        sa.Column("company_id", GUID(), nullable=True),
        # -- provider identity ---------------------------------------------------------
        sa.Column("provider", sa.String(ENUM_PROVIDER), nullable=False),
        sa.Column("external_id", sa.String(EXTERNAL_ID_MAX), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("apply_url", sa.Text(), nullable=True),
        # -- advertised content ----------------------------------------------------------
        sa.Column("title", sa.String(POSTING_TITLE_MAX), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(POSTING_LOCATION_MAX), nullable=True),
        sa.Column("work_arrangement", sa.String(ENUM_WORK_ARRANGEMENT), nullable=False),
        sa.Column("employment_type", sa.String(ENUM_EMPLOYMENT_TYPE), nullable=False),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(CURRENCY_LEN), nullable=True),
        sa.Column("posted_at", UTCDateTime(), nullable=True),
        sa.Column("closes_at", UTCDateTime(), nullable=True),
        sa.Column("raw_json", JSONType(), nullable=False),
        # -- deduplication and lifecycle ---------------------------------------------------
        sa.Column("content_hash", sa.String(SHA256_HEX), nullable=True),
        sa.Column("dedupe_key", sa.String(DEDUPE_KEY_MAX), nullable=True),
        sa.Column("status", sa.String(ENUM_POSTING_STATUS), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_job_postings"),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_job_postings_company_id_companies",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint(
            "provider", "external_id", name="uq_job_postings_provider_external_id"
        ),
    )
    op.create_index("ix_job_postings_company_id", "job_postings", ["company_id"], unique=False)
    op.create_index("ix_job_postings_posted_at", "job_postings", ["posted_at"], unique=False)
    # Not "is this the same job?" but "has this job's text changed since I last scored it?".
    op.create_index(
        "ix_job_postings_content_hash", "job_postings", ["content_hash"], unique=False
    )
    op.create_index("ix_job_postings_dedupe_key", "job_postings", ["dedupe_key"], unique=True)
    op.create_index("ix_job_postings_status", "job_postings", ["status"], unique=False)
    op.create_index("ix_job_postings_created_at", "job_postings", ["created_at"], unique=False)
    # The discovery feed's only query shape: filter by status, order by recency.
    op.create_index(
        "ix_job_postings_status_posted_at",
        "job_postings",
        ["status", "posted_at"],
        unique=False,
    )


def _create_job_scores() -> None:
    """Create ``job_scores`` — how well one posting fits one user."""
    op.create_table(
        "job_scores",
        _id_column(),
        _user_id_column(),
        sa.Column("posting_id", GUID(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("normalized", sa.Integer(), nullable=False),
        sa.Column("breakdown", JSONType(), nullable=False),
        sa.Column("verdict", sa.String(VERDICT_MAX), nullable=True),
        sa.Column("model_used", sa.String(MODEL_NAME_MAX), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_job_scores"),
        _user_fk("job_scores"),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["job_postings.id"],
            name="fk_job_scores_posting_id_job_postings",
            ondelete="CASCADE",
        ),
        # One current score per (posting, user): re-scoring upserts, never appends.
        sa.UniqueConstraint(
            "posting_id", "user_id", name="uq_job_scores_posting_id_user_id"
        ),
    )
    op.create_index("ix_job_scores_user_id", "job_scores", ["user_id"], unique=False)
    op.create_index("ix_job_scores_posting_id", "job_scores", ["posting_id"], unique=False)
    op.create_index("ix_job_scores_normalized", "job_scores", ["normalized"], unique=False)
    op.create_index("ix_job_scores_verdict", "job_scores", ["verdict"], unique=False)
    op.create_index("ix_job_scores_created_at", "job_scores", ["created_at"], unique=False)


# ======================================================================================
# Documents and applications
# ======================================================================================


def _create_resumes() -> None:
    """Create ``resumes`` — named variants, holding configuration but no content."""
    op.create_table(
        "resumes",
        _id_column(),
        _user_id_column(),
        sa.Column("name", sa.String(RESUME_NAME_MAX), nullable=False),
        sa.Column("variant_label", sa.String(RESUME_NAME_MAX), nullable=True),
        sa.Column(
            "template",
            sa.String(RESUME_TEMPLATE_MAX),
            server_default=DEFAULT_TEMPLATE,
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), server_default=ZERO, nullable=False),
        sa.Column("config", JSONType(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_resumes"),
        _user_fk("resumes"),
    )
    op.create_index("ix_resumes_user_id", "resumes", ["user_id"], unique=False)
    # Exactly one default per user is enforced by the application layer: a partial unique
    # index is not portable to SQLite, so this index only serves the lookup.
    op.create_index("ix_resumes_is_default", "resumes", ["is_default"], unique=False)
    op.create_index("ix_resumes_created_at", "resumes", ["created_at"], unique=False)


def _deferred_application_fks() -> tuple[sa.ForeignKeyConstraint, ...]:
    """Return the two foreign keys that close the ``applications`` ⇄ documents cycle.

    Built by a function rather than held as module constants because a
    :class:`~sqlalchemy.ForeignKeyConstraint` instance belongs to exactly one table and
    cannot be reused between the inline (SQLite) and ``ALTER`` (PostgreSQL) paths.

    Returns:
        Fresh constraint objects for ``resume_version_id`` and ``cover_letter_id``.
    """
    return (
        sa.ForeignKeyConstraint(
            ["resume_version_id"],
            ["resume_versions.id"],
            name="fk_applications_resume_version_id_resume_versions",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
            name="fk_applications_cover_letter_id_cover_letters",
            ondelete="SET NULL",
        ),
    )


def _create_applications(bind: sa.engine.Connection) -> None:
    """Create ``applications`` — the table that guarantees "never apply twice".

    On a backend without ``ALTER TABLE ... ADD CONSTRAINT`` (SQLite) the two cyclic foreign
    keys are declared inline, referencing tables that do not exist yet — SQLite resolves
    foreign key targets lazily, and this is exactly what ``create_all`` emits there.
    Everywhere else they are omitted here and added by
    :func:`_create_deferred_application_foreign_keys` once the referenced tables exist.

    Args:
        bind: The connection migrations are running on.
    """
    inline_cycle_fks = () if bind.dialect.supports_alter else _deferred_application_fks()
    op.create_table(
        "applications",
        _id_column(),
        _user_id_column(),
        # -- subject --------------------------------------------------------------------
        sa.Column("posting_id", GUID(), nullable=False),
        sa.Column("company_id", GUID(), nullable=True),
        sa.Column("session_id", GUID(), nullable=True),
        sa.Column("status", sa.String(ENUM_APPLICATION_STATUS), nullable=False),
        # -- submitted documents (foreign keys added by ALTER; see module docstring) -----
        sa.Column("resume_version_id", GUID(), nullable=True),
        sa.Column("cover_letter_id", GUID(), nullable=True),
        # -- submission outcome -----------------------------------------------------------
        sa.Column("submitted_at", UTCDateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("confirmation_screenshot_id", GUID(), nullable=True),
        sa.Column("confirmation_id", sa.String(CONFIRMATION_ID_MAX), nullable=True),
        sa.Column("confirmation_text", sa.Text(), nullable=True),
        sa.Column(
            "external_application_id", sa.String(CONFIRMATION_ID_MAX), nullable=True
        ),
        # -- review, retries and evidence ---------------------------------------------------
        sa.Column("review_reason", sa.String(ENUM_REVIEW_REASON), nullable=True),
        sa.Column("review_payload", JSONType(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=ZERO, nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("answers", JSONType(), nullable=False),
        sa.Column("ai_reasoning", sa.Text(), nullable=True),
        sa.Column("browser_log", JSONType(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_applications"),
        _user_fk("applications"),
        # RESTRICT, not CASCADE. Cascading would silently erase the evidence that a posting
        # was already applied to; discovery would then rediscover the same job under a fresh
        # primary key and the unique constraint below would no longer recognise it.
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["job_postings.id"],
            name="fk_applications_posting_id_job_postings",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_applications_company_id_companies",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["run_sessions.id"],
            name="fk_applications_session_id_run_sessions",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["confirmation_screenshot_id"],
            ["uploaded_files.id"],
            name="fk_applications_confirmation_screenshot_id_uploaded_files",
            ondelete="SET NULL",
        ),
        *inline_cycle_fks,
        # Golden rule #1, at the only layer a bug cannot bypass.
        sa.UniqueConstraint("user_id", "posting_id", name="uq_applications_user_posting"),
    )
    op.create_index("ix_applications_user_id", "applications", ["user_id"], unique=False)
    op.create_index(
        "ix_applications_posting_id", "applications", ["posting_id"], unique=False
    )
    op.create_index(
        "ix_applications_company_id", "applications", ["company_id"], unique=False
    )
    op.create_index(
        "ix_applications_session_id", "applications", ["session_id"], unique=False
    )
    op.create_index("ix_applications_status", "applications", ["status"], unique=False)
    op.create_index(
        "ix_applications_resume_version_id",
        "applications",
        ["resume_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_applications_cover_letter_id",
        "applications",
        ["cover_letter_id"],
        unique=False,
    )
    op.create_index(
        "ix_applications_submitted_at", "applications", ["submitted_at"], unique=False
    )
    op.create_index(
        "ix_applications_confirmation_screenshot_id",
        "applications",
        ["confirmation_screenshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_applications_external_application_id",
        "applications",
        ["external_application_id"],
        unique=False,
    )
    op.create_index(
        "ix_applications_review_reason", "applications", ["review_reason"], unique=False
    )
    op.create_index(
        "ix_applications_created_at", "applications", ["created_at"], unique=False
    )
    # The applications list is always user-scoped and almost always status-filtered.
    op.create_index(
        "ix_applications_user_id_status",
        "applications",
        ["user_id", "status"],
        unique=False,
    )


def _create_resume_versions() -> None:
    """Create ``resume_versions`` — immutable generations with full provenance.

    ``application_id`` is ``SET NULL`` rather than ``CASCADE``: golden rule #6 keeps
    ``content_json`` forever, even past the application it was tailored for. ``file_id`` is
    ``SET NULL`` for the same reason in the other direction — the artifact is disposable.
    """
    op.create_table(
        "resume_versions",
        _id_column(),
        sa.Column("resume_id", GUID(), nullable=False),
        sa.Column("application_id", GUID(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_json", JSONType(), nullable=False),
        sa.Column(
            "render_format",
            sa.String(RENDER_FORMAT_MAX),
            server_default=DEFAULT_RENDER_FORMAT,
            nullable=False,
        ),
        sa.Column("file_id", GUID(), nullable=True),
        sa.Column("fact_ids", JSONType(), nullable=False),
        sa.Column("token_usage", JSONType(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        *_timestamp_columns(),
        _deleted_at_column(),
        sa.PrimaryKeyConstraint("id", name="pk_resume_versions"),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name="fk_resume_versions_resume_id_resumes",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name="fk_resume_versions_application_id_applications",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["uploaded_files.id"],
            name="fk_resume_versions_file_id_uploaded_files",
            ondelete="SET NULL",
        ),
        # Gapless, race-free version sequence per variant.
        sa.UniqueConstraint(
            "resume_id",
            "version_number",
            name="uq_resume_versions_resume_id_version_number",
        ),
    )
    op.create_index(
        "ix_resume_versions_resume_id", "resume_versions", ["resume_id"], unique=False
    )
    op.create_index(
        "ix_resume_versions_application_id",
        "resume_versions",
        ["application_id"],
        unique=False,
    )
    op.create_index("ix_resume_versions_file_id", "resume_versions", ["file_id"], unique=False)
    op.create_index(
        "ix_resume_versions_created_at", "resume_versions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_resume_versions_deleted_at", "resume_versions", ["deleted_at"], unique=False
    )


def _create_cover_letters() -> None:
    """Create ``cover_letters`` — one letter per posting, optionally per application."""
    op.create_table(
        "cover_letters",
        _id_column(),
        _user_id_column(),
        sa.Column("posting_id", GUID(), nullable=False),
        sa.Column("application_id", GUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "tone", sa.String(TONE_MAX), server_default=DEFAULT_TONE, nullable=False
        ),
        sa.Column("file_id", GUID(), nullable=True),
        sa.Column("token_usage", JSONType(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_cover_letters"),
        _user_fk("cover_letters"),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["job_postings.id"],
            name="fk_cover_letters_posting_id_job_postings",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name="fk_cover_letters_application_id_applications",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["uploaded_files.id"],
            name="fk_cover_letters_file_id_uploaded_files",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_cover_letters_user_id", "cover_letters", ["user_id"], unique=False)
    op.create_index(
        "ix_cover_letters_posting_id", "cover_letters", ["posting_id"], unique=False
    )
    op.create_index(
        "ix_cover_letters_application_id",
        "cover_letters",
        ["application_id"],
        unique=False,
    )
    op.create_index("ix_cover_letters_file_id", "cover_letters", ["file_id"], unique=False)
    op.create_index(
        "ix_cover_letters_created_at", "cover_letters", ["created_at"], unique=False
    )


def _create_application_events() -> None:
    """Create ``application_events`` — the append-only submission audit trail."""
    op.create_table(
        "application_events",
        _id_column(),
        sa.Column("application_id", GUID(), nullable=False),
        sa.Column("kind", sa.String(EVENT_KIND_MAX), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("payload", JSONType(), nullable=False),
        sa.Column("at", UTCDateTime(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id", name="pk_application_events"),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name="fk_application_events_application_id_applications",
            ondelete="CASCADE",
        ),
    )
    # The only query shape: one application's trail, in chronological order. There is no
    # standalone index on application_id because this composite serves that lookup too.
    op.create_index(
        "ix_application_events_application_id_at",
        "application_events",
        ["application_id", "at"],
        unique=False,
    )
    op.create_index(
        "ix_application_events_created_at",
        "application_events",
        ["created_at"],
        unique=False,
    )


# ======================================================================================
# The applications <-> documents cycle
# ======================================================================================


def _create_deferred_application_foreign_keys(bind: sa.engine.Connection) -> None:
    """Add the two cyclic foreign keys by ``ALTER``, on backends that support it.

    ``applications.resume_version_id`` and ``applications.cover_letter_id`` point at tables
    whose own ``application_id`` columns point back, so neither table can be created with
    both constraints in place. On PostgreSQL the cycle is closed here, after all three tables
    exist. On SQLite there is nothing to do: :func:`_create_applications` already declared
    both constraints inline, because that dialect resolves foreign key targets lazily and
    offers no ``ALTER`` alternative.

    Args:
        bind: The connection migrations are running on.
    """
    if not bind.dialect.supports_alter:
        return
    op.create_foreign_key(
        "fk_applications_resume_version_id_resume_versions",
        "applications",
        "resume_versions",
        ["resume_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_applications_cover_letter_id_cover_letters",
        "applications",
        "cover_letters",
        ["cover_letter_id"],
        ["id"],
        ondelete="SET NULL",
    )


def _drop_deferred_application_foreign_keys(bind: sa.engine.Connection) -> None:
    """Break the ``applications`` ⇄ documents cycle before the drop sweep.

    ``cover_letters`` and ``resume_versions`` are dropped while ``applications`` still
    exists, so the pointers into them have to go first. How depends on the backend:

    * With ``ALTER``, the two constraints are dropped outright.
    * Without it (SQLite), the constraints are inline and cannot be removed — so the
      referencing *values* are cleared instead. SQLite performs an implicit ``DELETE`` when
      dropping a table and raises on any surviving foreign key reference to it; nulling both
      columns removes every such reference. Losing those two pointers is irrelevant: the
      tables holding them are about to be dropped by the caller.

    Args:
        bind: The connection migrations are running on.
    """
    if not bind.dialect.supports_alter:
        op.execute(
            "UPDATE applications SET resume_version_id = NULL, cover_letter_id = NULL"
        )
        return
    op.drop_constraint(
        "fk_applications_cover_letter_id_cover_letters",
        "applications",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_applications_resume_version_id_resume_versions",
        "applications",
        type_="foreignkey",
    )
