/**
 * The TypeScript mirror of `app/schemas/` and `app/models/enums.py`.
 *
 * `docs/CONTRACTS.md` §18 makes this file binding: **enum string values must match the
 * Python character-for-character.** A drift here does not fail loudly — it produces a filter
 * that matches nothing, a badge with no colour, and a screen that renders empty while the
 * network tab shows a 200. Every value below was generated by reading `app/models/enums.py`
 * and the live OpenAPI document served by `app.main:app`, not from memory.
 *
 * Two conventions, applied throughout:
 *
 * **Enums are ordered tuples, not TypeScript `enum`s.** `const X = [...] as const` plus
 * `type X = (typeof X)[number]` gives the union type *and* a runtime list in declaration
 * order — which is what a filter dropdown, a legend, and a status-group header all need.
 * A TypeScript `enum` gives neither, and `isolatedModules` makes `const enum` unusable.
 *
 * **Optionality mirrors pydantic, not convenience.** A field the server always sends is
 * required here; a field with a default is `?`; a field typed `X | None` is `X | null`.
 * `noUncheckedIndexedAccess` plus honest optionality is what catches "the API stopped
 * sending `score`" at compile time in the one place it can still be cheap to fix.
 */

/** ISO-8601 timestamp with timezone, e.g. `2026-08-08T09:41:02.113471+00:00`. */
export type IsoDateTime = string;

/** ISO-8601 calendar date, e.g. `2026-08-08`. */
export type IsoDate = string;

/** A UUID rendered as a string. Every id in this API is one. */
export type Uuid = string;

/** Free-form JSON object, as produced by a pydantic `dict[str, Any]` field. */
export type JsonObject = Record<string, unknown>;

/**
 * Bumped on **any** DTO shape change in this file.
 *
 * It is half of the persisted-cache buster (`docs/UI.md` §10.5): a restored cache entry
 * written by a build whose `ApplicationRead` had different fields is not merely stale, it is
 * wrong, and rendering it produces `undefined` in places the types promise are populated.
 * The other half is `__APP_VERSION__`.
 */
export const API_SCHEMA_VERSION = 1;

/** Prefix every REST route in this file carries. `/health`, `/ready`, `/metrics` and `/ws` do not. */
export const API_PREFIX = '/api/v1';

/** Fixed page size (`DEFAULT_PAGE_LIMIT` in `app/schemas/common.py`). */
export const PAGE_LIMIT = 50;

/** Server-side ceiling on `limit` (`MAX_PAGE_LIMIT`). */
export const MAX_PAGE_LIMIT = 200;

// ══════════════════════════════════════════════════════════════════════════════════════
// Enums — app/models/enums.py
// ══════════════════════════════════════════════════════════════════════════════════════

/** Applicant-tracking systems ApplicantOS can talk to. */
export const ATS_PROVIDER_NAMES = [
  'linkedin',
  'greenhouse',
  'lever',
  'ashby',
  'workday',
  'manual',
] as const;
export type ATSProviderName = (typeof ATS_PROVIDER_NAMES)[number];

/**
 * Providers that support real automated submission (`docs/CONTRACTS.md` §9).
 *
 * LinkedIn's ToS prohibits automated submission and Workday's account-gated multi-step flow
 * routes to review by design, so both are discovery-only. The UI must never offer "Apply
 * now" for a posting whose provider is not in this set.
 */
export const AUTO_APPLY_PROVIDERS: ReadonlySet<ATSProviderName> = new Set<ATSProviderName>([
  'greenhouse',
  'lever',
  'ashby',
]);

/** Lifecycle of a discovered job posting. */
export const POSTING_STATUSES = [
  'discovered',
  'deduped',
  'scored',
  'queued',
  'processing',
  'applied',
  'skipped',
  'needs_review',
  'failed',
  'expired',
] as const;
export type PostingStatus = (typeof POSTING_STATUSES)[number];

/** Posting statuses from which the pipeline never advances. Mirrors `POSTING_TERMINAL_STATES`. */
export const POSTING_TERMINAL_STATES: ReadonlySet<PostingStatus> = new Set<PostingStatus>([
  'applied',
  'skipped',
  'failed',
  'expired',
]);

/** Lifecycle of a single application to a single posting. All thirteen values. */
export const APPLICATION_STATUSES = [
  'draft',
  'preparing',
  'ready',
  'submitting',
  'submitted',
  'confirmed',
  'needs_review',
  'failed',
  'abandoned',
  'rejected',
  'interview',
  'offer',
  'ghosted',
] as const;
export type ApplicationStatus = (typeof APPLICATION_STATUSES)[number];

/** Statuses that end an application's life. Mirrors `APPLICATION_TERMINAL_STATES`. */
export const APPLICATION_TERMINAL_STATES: ReadonlySet<ApplicationStatus> =
  new Set<ApplicationStatus>(['failed', 'abandoned', 'rejected', 'offer', 'ghosted']);

/**
 * Statuses that mean the employer already holds this application.
 *
 * Golden rule #1 — the UI must not offer a submit affordance from any of these, even though
 * the server refuses independently.
 */
export const APPLICATION_POST_SUBMIT_STATES: ReadonlySet<ApplicationStatus> =
  new Set<ApplicationStatus>([
    'submitted',
    'confirmed',
    'rejected',
    'interview',
    'offer',
    'ghosted',
  ]);

/** Statuses in which nothing has been transmitted to the employer. */
export const APPLICATION_PRE_SUBMIT_STATES: ReadonlySet<ApplicationStatus> =
  new Set<ApplicationStatus>(['draft', 'preparing', 'ready', 'submitting']);

/**
 * The three statuses that animate their StatusDot (`docs/UI.md` §2.4 rule 1).
 *
 * "Animated = in flight" is what makes a 40-row table readable in peripheral vision, so this
 * set is the whole rule: everything outside it is static.
 */
export const APPLICATION_IN_FLIGHT_STATES: ReadonlySet<ApplicationStatus> =
  new Set<ApplicationStatus>(['preparing', 'submitting', 'needs_review']);

/** Why an application was routed to the human review queue. All fourteen reasons. */
export const REVIEW_REASONS = [
  'too_many_essays',
  'unknown_field',
  'login_required',
  'captcha',
  'mfa',
  'file_upload_failed',
  'ambiguous_answer',
  'low_confidence',
  'policy_block',
  'submit_not_found',
  'unsupported_flow',
  'verification_failed',
  'rate_limited',
  'insufficient_knowledge',
] as const;
export type ReviewReason = (typeof REVIEW_REASONS)[number];

/** Classification for every file ApplicantOS stores or generates. */
export const DOCUMENT_KINDS = [
  'master_resume',
  'tailored_resume',
  'cover_letter',
  'screenshot',
  'transcript',
  'portfolio',
  'source_document',
  'other',
] as const;
export type DocumentKind = (typeof DOCUMENT_KINDS)[number];

/** Employment arrangement advertised by a posting. */
export const EMPLOYMENT_TYPES = [
  'full_time',
  'part_time',
  'internship',
  'contract',
  'new_grad',
  'unknown',
] as const;
export type EmploymentType = (typeof EMPLOYMENT_TYPES)[number];

/** Where the work is performed. `unknown` is a first-class value, never a guess. */
export const WORK_ARRANGEMENTS = ['remote', 'hybrid', 'onsite', 'unknown'] as const;
export type WorkArrangement = (typeof WORK_ARRANGEMENTS)[number];

/** Type of an application-form input discovered by the browser autofiller. */
export const FIELD_KINDS = [
  'text',
  'textarea',
  'select',
  'multiselect',
  'radio',
  'checkbox',
  'file',
  'date',
  'number',
  'email',
  'phone',
  'url',
  'unknown',
] as const;
export type FieldKind = (typeof FIELD_KINDS)[number];

/**
 * The extension points of ApplicantOS.
 *
 * There is no `'parser'` kind: document reading is one module dispatching on content, not
 * a registry extension point. See `PluginKind` in `app/models/enums.py`.
 */
export const PLUGIN_KINDS = [
  'provider',
  'model',
  'template',
  'analyzer',
  'tracker',
] as const;
export type PluginKind = (typeof PLUGIN_KINDS)[number];

/** Node types in the user's knowledge graph. */
export const ENTITY_KINDS = [
  'person',
  'skill',
  'technology',
  'project',
  'organization',
  'role',
  'education',
  'award',
  'certification',
  'course',
  'leadership',
  'publication',
  'interest',
  'goal',
  'language',
] as const;
export type EntityKind = (typeof ENTITY_KINDS)[number];

/** Edge types in the user's knowledge graph. */
export const RELATION_KINDS = [
  'used_in',
  'worked_at',
  'built',
  'studied_at',
  'earned',
  'led',
  'contributed_to',
  'related_to',
  'published',
  'mentored',
  'achieved',
  'requires',
] as const;
export type RelationKind = (typeof RELATION_KINDS)[number];

/** Provenance of a knowledge document. Every fact traces back to one of these. */
export const SOURCE_KINDS = [
  'github_repo',
  'github_profile',
  'portfolio_page',
  'personal_website',
  'project_folder',
  'resume',
  'cover_letter',
  'readme',
  'documentation',
  'linkedin_export',
  'interview_note',
  'user_correction',
  'generated_resume',
  'blog_post',
  'video',
  'manual_entry',
] as const;
export type SourceKind = (typeof SOURCE_KINDS)[number];

/** Category of an atomic, source-attributed claim about the user. */
export const FACT_KINDS = [
  'accomplishment',
  'responsibility',
  'metric',
  'skill_usage',
  'award',
  'education_item',
  'leadership_item',
  'publication_item',
] as const;
export type FactKind = (typeof FACT_KINDS)[number];

/** Indexing state of a knowledge source. */
export const INDEX_STATUSES = [
  'pending',
  'indexing',
  'indexed',
  'failed',
  'skipped',
  'stale',
] as const;
export type IndexStatus = (typeof INDEX_STATUSES)[number];

/** Index statuses in which no work is currently in flight or queued. */
export const INDEX_TERMINAL_STATES: ReadonlySet<IndexStatus> = new Set<IndexStatus>([
  'indexed',
  'failed',
  'skipped',
]);

/** Category of a memory entry — the system's feedback loop. */
export const MEMORY_KINDS = [
  'correction',
  'outcome',
  'feedback',
  'preference',
  'note',
] as const;
export type MemoryKind = (typeof MEMORY_KINDS)[number];

/** State of an automation run session. */
export const SESSION_STATUSES = ['running', 'completed', 'failed', 'cancelled'] as const;
export type SessionStatus = (typeof SESSION_STATUSES)[number];

/** Session statuses that mean execution has stopped. */
export const SESSION_FINISHED_STATES: ReadonlySet<SessionStatus> = new Set<SessionStatus>([
  'completed',
  'failed',
  'cancelled',
]);

/** State of a resumable checkpoint step. */
export const CHECKPOINT_STATUSES = [
  'pending',
  'running',
  'succeeded',
  'failed',
  'compensated',
] as const;
export type CheckpointStatus = (typeof CHECKPOINT_STATUSES)[number];

/** The user's right-to-work status in the hiring country. Never inferred. */
export const WORK_AUTH_STATUSES = [
  'citizen',
  'permanent_resident',
  'visa_holder',
  'needs_sponsorship',
  'unknown',
] as const;
export type WorkAuthStatus = (typeof WORK_AUTH_STATUSES)[number];

/** The channel a status signal was observed on (`docs/CONTRACTS.md` §17). */
export const SIGNAL_SOURCES = [
  'email_gmail',
  'email_imap',
  'email_outlook',
  'ats_portal',
  'manual',
  'webhook',
] as const;
export type SignalSource = (typeof SIGNAL_SOURCES)[number];

/** Signal sources backed by a mailbox, governed by the §17.8 privacy invariants. */
export const EMAIL_SIGNAL_SOURCES: ReadonlySet<SignalSource> = new Set<SignalSource>([
  'email_gmail',
  'email_imap',
  'email_outlook',
]);

/** What a status signal actually says about an application. */
export const SIGNAL_KINDS = [
  'application_received',
  'viewed',
  'assessment_requested',
  'interview_invite',
  'offer',
  'rejection',
  'withdrawn',
  'ghosted_inferred',
  'unknown',
] as const;
export type SignalKind = (typeof SIGNAL_KINDS)[number];

/**
 * What each signal kind means in `ApplicationStatus` terms. Mirrors `SIGNAL_KIND_TO_STATUS`.
 *
 * `viewed` and `unknown` map to `null` on purpose: a view is real information for analytics
 * but says nothing about the outcome, and an unclassifiable message must never move anything.
 */
export const SIGNAL_KIND_TO_STATUS: Readonly<Record<SignalKind, ApplicationStatus | null>> = {
  application_received: 'submitted',
  viewed: null,
  assessment_requested: 'needs_review',
  interview_invite: 'interview',
  offer: 'offer',
  rejection: 'rejected',
  withdrawn: 'abandoned',
  ghosted_inferred: 'ghosted',
  unknown: null,
};

/** The mailbox implementation behind an email account. All read-only. */
export const MAIL_PROVIDERS = ['gmail', 'outlook', 'imap'] as const;
export type MailProvider = (typeof MAIL_PROVIDERS)[number];

/** Mailbox implementation to the source recorded on every signal it produces. */
export const MAIL_PROVIDER_TO_SIGNAL_SOURCE: Readonly<Record<MailProvider, SignalSource>> = {
  gmail: 'email_gmail',
  outlook: 'email_outlook',
  imap: 'email_imap',
};

/**
 * Where an application's *current* status came from.
 *
 * `manual` is the default and the highest authority: the human said so, and a
 * lower-confidence inference must never silently overwrite it.
 */
export const STATUS_SOURCES = ['manual', 'email', 'portal', 'inferred', 'pipeline'] as const;
export type StatusSource = (typeof STATUS_SOURCES)[number];

/** Verdict attached to a score by the rule pack. */
export const SCORE_VERDICTS = ['apply', 'review', 'skip'] as const;
export type ScoreVerdict = (typeof SCORE_VERDICTS)[number];

/** When the pipeline attaches a cover letter. */
export const COVER_LETTER_POLICIES = [
  'always',
  'when_required',
  'when_high_score',
  'never',
] as const;
export type CoverLetterPolicy = (typeof COVER_LETTER_POLICIES)[number];

/** Steps of the onboarding wizard, in order. Path segment of `POST /onboarding/steps/{step}`. */
export const ONBOARDING_STEPS = [
  'identity',
  'contact',
  'work_authorization',
  'demographics',
  'preferences',
  'links',
  'sources',
  'master_resume',
] as const;
export type OnboardingStepKey = (typeof ONBOARDING_STEPS)[number];

/** Render targets for a resume preview. */
export const RENDER_FORMATS = ['pdf', 'docx', 'md', 'html'] as const;
export type RenderFormat = (typeof RENDER_FORMATS)[number];

/** Log levels as emitted by structlog and stored on `log_entries.level`. */
export const LOG_LEVELS = ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'] as const;
export type LogLevel = (typeof LOG_LEVELS)[number];

// ══════════════════════════════════════════════════════════════════════════════════════
// Envelopes — app/schemas/common.py
// ══════════════════════════════════════════════════════════════════════════════════════

/** The return shape of every list endpoint. */
export interface Page<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
  /** Derived server-side from `offset + items.length < total`, so a short final page is correct. */
  has_more: boolean;
}

/** The single error body every failing endpoint returns. Clients branch on `error`, never `detail`. */
export interface ErrorResponse {
  /** Stable machine-readable code — see {@link API_ERROR_CODES}. */
  error: string;
  detail?: string | null;
  /** Turns a screenshot of an error toast into a log query. */
  correlation_id?: string | null;
}

/** Acknowledgement returned by endpoints whose only answer is "done". */
export interface OkResponse {
  ok: boolean;
  message?: string | null;
  data: JsonObject;
}

/**
 * Stable machine codes from `app/api/errors.py`. Part of the published contract.
 *
 * Not exhaustive as a *type* — a newer backend may add one — which is why callers switch
 * with a default branch rather than relying on exhaustiveness.
 */
export const API_ERROR_CODES = [
  'not_found',
  'invalid_request',
  'validation_error',
  'conflict',
  'internal_error',
  'provider_error',
  'provider_auth_required',
  'rate_limited',
  'posting_unavailable',
  'unsupported_flow',
  'document_render_failed',
  'plugin_not_found',
  'plugin_disabled',
  'plugin_failed',
] as const;
export type ApiErrorCode = (typeof API_ERROR_CODES)[number] | (string & {});

// ══════════════════════════════════════════════════════════════════════════════════════
// Health — app/schemas + app/api/routes/health.py
// ══════════════════════════════════════════════════════════════════════════════════════

export interface HealthReport {
  status: string;
  app: string;
  version: string;
  environment: string;
}

export interface DependencyStatus {
  ok: boolean;
  required: boolean;
  skipped: boolean;
  detail?: string | null;
}

export interface ReadinessReport {
  ready: boolean;
  checks: Record<string, DependencyStatus>;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Companies, postings, scores
// ══════════════════════════════════════════════════════════════════════════════════════

export interface CompanyRead {
  id: Uuid;
  name: string;
  normalized_name: string;
  domain?: string | null;
  industry?: string | null;
  size_bucket?: string | null;
  employee_count?: number | null;
  is_defense: boolean;
  is_startup: boolean;
  metadata_json: JsonObject;
  enriched_at?: IsoDateTime | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** One line of a score's arithmetic: a rule that fired, and what it contributed. */
export interface ScoreComponentRead {
  key: string;
  label: string;
  points: number;
  weight: number;
  matched: boolean;
  /** A hard negative zeroes the score outright; render it as danger text with a `−` prefix. */
  hard_negative: boolean;
  detail?: string | null;
}

/** How well one posting fits one user, with the reasoning attached. */
export interface ScoreRead {
  id: Uuid;
  posting_id: Uuid;
  user_id: Uuid;
  total: number;
  /** 0–100. The value the ScoreBar renders and `min_score` is compared against. */
  normalized: number;
  breakdown: JsonObject;
  components: ScoreComponentRead[];
  verdict?: ScoreVerdict | null;
  model_used?: string | null;
  rationale?: string | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** The list-row projection of a posting. */
export interface PostingSummary {
  id: Uuid;
  title: string;
  provider: ATSProviderName;
  url: string;
  apply_url?: string | null;
  location?: string | null;
  work_arrangement: WorkArrangement;
  employment_type: EmploymentType;
  salary_min?: number | null;
  salary_max?: number | null;
  salary_currency?: string | null;
  posted_at?: IsoDateTime | null;
  closes_at?: IsoDateTime | null;
  status: PostingStatus;
  company_id?: Uuid | null;
  company?: CompanyRead | null;
  is_open: boolean;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** A posting in full, for the detail view. */
export interface PostingRead extends PostingSummary {
  external_id: string;
  description?: string | null;
  content_hash?: string | null;
  dedupe_key?: string | null;
  score?: ScoreRead | null;
}

/** Body of `POST /postings/discover` — one manual discovery run. */
export interface DiscoverRequest {
  providers?: ATSProviderName[];
  keywords?: string[];
  locations?: string[];
  remote_only?: boolean;
  posted_within_days?: number | null;
  limit?: number;
  extra?: JsonObject;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Applications
// ══════════════════════════════════════════════════════════════════════════════════════

/** A stored file produced or consumed by an application. */
export interface ArtifactRead {
  id: Uuid;
  kind: DocumentKind;
  filename: string;
  content_type?: string | null;
  size_bytes: number;
  /** Relative download path on the backend, or `null` when the blob is gone. */
  url?: string | null;
  created_at: IsoDateTime;
}

/** One append-only entry in an application's audit trail. Drives the Timeline. */
export interface ApplicationEventRead {
  id: Uuid;
  application_id: Uuid;
  kind: string;
  message?: string | null;
  payload: JsonObject;
  at: IsoDateTime;
  created_at: IsoDateTime;
}

/** One user's application to one posting — the list projection. */
export interface ApplicationRead {
  id: Uuid;
  user_id: Uuid;
  posting_id: Uuid;
  company_id?: Uuid | null;
  session_id?: Uuid | null;
  status: ApplicationStatus;
  submitted_at?: IsoDateTime | null;
  duration_seconds?: number | null;
  confirmation_id?: string | null;
  external_application_id?: string | null;
  review_reason?: ReviewReason | null;
  attempt_count: number;
  last_error?: string | null;
  notes?: string | null;
  posting?: PostingSummary | null;
  company?: CompanyRead | null;
  score?: ScoreRead | null;
  /** Server-computed: false once the status is post-submit (golden rule #1). */
  can_submit: boolean;
  needs_review: boolean;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** Everything the application detail screen renders. */
export interface ApplicationDetail extends ApplicationRead {
  resume_version?: ResumeVersionRead | null;
  cover_letter?: CoverLetterRead | null;
  events: ApplicationEventRead[];
  artifacts: ArtifactRead[];
  artifact_urls: string[];
  answers: JsonObject;
  ai_reasoning?: string | null;
  review_payload: JsonObject;
  browser_log: JsonObject[];
  confirmation_text?: string | null;
  confirmation_screenshot_id?: Uuid | null;
}

/** Body of `PATCH /applications/{id}`. */
export interface ApplicationUpdate {
  status?: ApplicationStatus | null;
  notes?: string | null;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Review queue
// ══════════════════════════════════════════════════════════════════════════════════════

/** A form field the automation refused to answer rather than guess at. */
export interface ReviewField {
  selector: string;
  label: string;
  kind: FieldKind;
  required: boolean;
  options: string[];
  max_length?: number | null;
  hint?: string | null;
  /** Present but below the confidence floor. Never pre-filled without showing its confidence. */
  suggested_answer?: string | null;
  confidence?: number | null;
}

/** One entry in the human review queue. */
export interface ReviewItem {
  application: ApplicationRead;
  reason?: ReviewReason | null;
  unanswered_fields: ReviewField[];
  payload: JsonObject;
}

/** Body of `POST /reviews/{id}/resolve` — a human's answers, keyed by field selector. */
export interface ReviewResolve {
  answers: JsonObject;
}

/** Body of `POST /reviews/{id}/dismiss`. */
export interface ReviewDismiss {
  note?: string | null;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Resumes and cover letters
// ══════════════════════════════════════════════════════════════════════════════════════

export interface ResumeContactSchema {
  name: string;
  email?: string | null;
  phone?: string | null;
  location?: string | null;
  website?: string | null;
  github?: string | null;
  linkedin?: string | null;
  portfolio?: string | null;
  links: Record<string, string>;
}

/** One experience, project, or education entry. */
export interface ResumeEntrySchema {
  title: string;
  organization?: string | null;
  location?: string | null;
  date_range?: string | null;
  bullets: string[];
  /** Golden rule #7: every bullet traces to a `KnowledgeFact.id`. This is that trace. */
  fact_ids: Uuid[];
}

export interface ResumeSectionSchema {
  heading: string;
  entries: ResumeEntrySchema[];
}

/** The structured resume — the permanent form; the rendered file is disposable. */
export interface ResumeDocumentSchema {
  contact: ResumeContactSchema;
  summary?: string | null;
  sections: ResumeSectionSchema[];
  skills_line?: string | null;
  meta: JsonObject;
}

/** One immutable generation of a resume, with full provenance. */
export interface ResumeVersionRead {
  id: Uuid;
  resume_id: Uuid;
  application_id?: Uuid | null;
  version_number: number;
  content_json: ResumeDocumentSchema;
  render_format: string;
  file_id?: Uuid | null;
  download_url?: string | null;
  fact_ids: Uuid[];
  token_usage: JsonObject;
  reasoning?: string | null;
  bullet_count: number;
  has_artifact: boolean;
  deleted_at?: IsoDateTime | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** A named resume variant — configuration, not content. */
export interface ResumeRead {
  id: Uuid;
  user_id: Uuid;
  name: string;
  variant_label?: string | null;
  template: string;
  is_default: boolean;
  config: JsonObject;
  version_count: number;
  latest_version?: ResumeVersionRead | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** Payload for creating a resume variant. */
export interface ResumeCreate {
  name: string;
  variant_label?: string | null;
  template?: string;
  is_default?: boolean;
  config?: JsonObject;
}

/** Body of `POST /resumes/preview` — tailor a resume without applying to anything. */
export interface ResumePreviewRequest {
  posting_id?: Uuid | null;
  resume_id?: Uuid | null;
  template?: string | null;
  variant_label?: string | null;
  max_bullets?: number;
  render_format?: RenderFormat;
  render?: boolean;
}

/** A cover letter drafted for one posting. */
export interface CoverLetterRead {
  id: Uuid;
  user_id: Uuid;
  posting_id: Uuid;
  application_id?: Uuid | null;
  body: string;
  tone: string;
  file_id?: Uuid | null;
  download_url?: string | null;
  token_usage: JsonObject;
  word_count: number;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Knowledge engine
// ══════════════════════════════════════════════════════════════════════════════════════

/** A registered knowledge source with its indexing state. */
export interface SourceRead {
  id: Uuid;
  user_id: Uuid;
  kind: SourceKind;
  uri: string;
  label?: string | null;
  config: JsonObject;
  enabled: boolean;
  index_status: IndexStatus;
  last_indexed_at?: IsoDateTime | null;
  last_error?: string | null;
  etag?: string | null;
  content_hash?: string | null;
  auto_refresh: boolean;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** Register something for the indexer to read. */
export interface SourceCreate {
  kind: SourceKind;
  uri: string;
  label?: string | null;
  config?: JsonObject;
  enabled?: boolean;
  auto_refresh?: boolean;
}

/** One atomic, source-attributed claim about the user. */
export interface FactRead {
  id: Uuid;
  user_id: Uuid;
  kind: FactKind;
  text: string;
  normalized_text: string;
  organization?: string | null;
  role?: string | null;
  location?: string | null;
  date_start?: IsoDate | null;
  date_end?: IsoDate | null;
  skills: string[];
  technologies: string[];
  metrics: string[];
  impact_score: number;
  confidence: number;
  source_document_id?: Uuid | null;
  entity_id?: Uuid | null;
  user_verified: boolean;
  is_active: boolean;
  content_hash: string;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
  has_embedding: boolean;
}

/** Body of `PATCH /knowledge/facts/{id}`. */
export interface FactUpdate {
  kind?: FactKind | null;
  text?: string | null;
  organization?: string | null;
  role?: string | null;
  location?: string | null;
  date_start?: IsoDate | null;
  date_end?: IsoDate | null;
  skills?: string[] | null;
  technologies?: string[] | null;
  metrics?: string[] | null;
  impact_score?: number | null;
  confidence?: number | null;
  user_verified?: boolean | null;
  is_active?: boolean | null;
}

/** A node in the user's knowledge graph. */
export interface EntityRead {
  id: Uuid;
  user_id: Uuid;
  kind: EntityKind;
  name: string;
  normalized_name: string;
  summary?: string | null;
  attributes: JsonObject;
  aliases: string[];
  confidence: number;
  mention_count: number;
  first_seen_at: IsoDateTime;
  last_seen_at: IsoDateTime;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
  has_embedding: boolean;
}

export interface GraphNode {
  id: Uuid;
  kind: EntityKind;
  label: string;
  summary?: string | null;
  mention_count: number;
  confidence: number;
  fact_count: number;
}

export interface GraphEdge {
  id: Uuid;
  source: Uuid;
  target: Uuid;
  relation: RelationKind;
  weight: number;
}

/** A renderable slice of the knowledge graph. */
export interface GraphView {
  nodes: GraphNode[];
  edges: GraphEdge[];
  stats: Record<string, number>;
}

/** One scored hit from `GET /knowledge/search`. */
export interface KnowledgeSearchResult {
  id: Uuid;
  kind: 'fact' | 'chunk' | 'entity' | 'memory';
  score: number;
  title?: string | null;
  text: string;
  source_uri?: string | null;
  metadata: JsonObject;
}

/** Aggregate counts behind `GET /knowledge/stats`. */
export interface KnowledgeStats {
  sources: number;
  sources_enabled: number;
  sources_failed: number;
  documents: number;
  chunks: number;
  chunks_embedded: number;
  entities: number;
  edges: number;
  facts: number;
  facts_active: number;
  facts_verified: number;
  memories: number;
  tokens_indexed: number;
  by_source_kind: Record<string, number>;
  by_entity_kind: Record<string, number>;
  by_fact_kind: Record<string, number>;
  last_indexed_at?: IsoDateTime | null;
}

/** Outcome of one indexing pass over one source. Mirrors `IndexReportRead`. */
export interface IndexReport {
  source_id: Uuid;
  documents: number;
  chunks: number;
  facts: number;
  entities: number;
  edges: number;
  /** The common and desirable case: the fingerprint had not moved. */
  skipped: boolean;
  duration_seconds: number;
  errors: string[];
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Sessions
// ══════════════════════════════════════════════════════════════════════════════════════

/** One automation run: its status, its timing, and every rollup counter. */
export interface SessionRead {
  id: Uuid;
  user_id: Uuid;
  status: SessionStatus;
  started_at: IsoDateTime;
  ended_at?: IsoDateTime | null;
  jobs_found: number;
  jobs_qualified: number;
  resumes_generated: number;
  applications_completed: number;
  manual_review: number;
  failures: number;
  avg_application_seconds?: number | null;
  token_usage: JsonObject;
  config_snapshot: JsonObject;
  trigger: string;
  duration_seconds?: number | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** A run plus the applications it produced. */
export interface SessionDetail extends SessionRead {
  applications: ApplicationRead[];
  checkpoints_pending: number;
  stats: Record<string, number>;
}

/** Body of `POST /sessions/start`. */
export interface SessionStartRequest {
  trigger?: string;
  discover?: DiscoverRequest | null;
  /** Overrides the persisted kill switch for this run only; `null` keeps the stored value. */
  auto_apply?: boolean | null;
  dry_run?: boolean | null;
  max_applications?: number | null;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Analytics
// ══════════════════════════════════════════════════════════════════════════════════════

/** The counter tiles on the home screen. */
export interface DashboardStats {
  applications_today: number;
  interviews: number;
  pending: number;
  rejected: number;
  needs_review: number;
  offers: number;
  total: number;
}

/** One stage of the discovery → offer funnel. */
export interface FunnelStage {
  key: string;
  label: string;
  count: number;
  /** Conversion from the *previous* stage, 0–1. */
  conversion_rate: number;
  share_of_total: number;
}

/** One day of activity. */
export interface TimeseriesPoint {
  date: IsoDate;
  discovered: number;
  scored: number;
  applications: number;
  submitted: number;
  interviews: number;
  offers: number;
  rejections: number;
}

/** One observational finding about what correlates with interviews. */
export interface InsightItem {
  key: string;
  title: string;
  detail?: string | null;
  sentiment: 'positive' | 'negative' | 'neutral';
  metric?: number | null;
  sample_size: number;
  /** False when the sample is too small to draw the conclusion; render it as such. */
  is_significant: boolean;
  context: JsonObject;
}

/** The full analytics payload — `GET /analytics/overview`. */
export interface AnalyticsOverview {
  stats: DashboardStats;
  funnel: FunnelStage[];
  timeseries: TimeseriesPoint[];
  insights: InsightItem[];
  by_provider: Record<string, number>;
  by_company: Record<string, number>;
  by_status: Record<string, number>;
  response_rate: number;
  interview_rate: number;
  offer_rate: number;
  avg_application_seconds?: number | null;
  avg_score?: number | null;
  tokens_used: Record<string, number>;
  window_days: number;
  generated_at?: IsoDateTime | null;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Profile, preferences, settings
// ══════════════════════════════════════════════════════════════════════════════════════

/** Every column of `user_profiles`, as returned by the API. */
export interface ProfileRead {
  id: Uuid;
  user_id: Uuid;
  phone?: string | null;
  pronouns?: string | null;
  location?: string | null;
  address: JsonObject;
  links: JsonObject;
  citizenship?: string | null;
  work_authorization: WorkAuthStatus;
  requires_sponsorship: boolean;
  /** EEO fields. Never inferred; always answerable as "decline to self-identify". */
  veteran_status?: string | null;
  gender?: string | null;
  race_ethnicity?: string | null;
  disability_status?: string | null;
  clearance?: string | null;
  salary_min?: number | null;
  salary_max?: number | null;
  salary_currency: string;
  remote_preference: WorkArrangement;
  willing_to_relocate: boolean;
  relocation_targets: string[];
  desired_roles: string[];
  desired_industries: string[];
  excluded_companies: string[];
  excluded_industries: string[];
  education: JsonObject[];
  start_date_availability?: IsoDate | null;
  notice_period_weeks?: number | null;
  extra: JsonObject;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** Partial update to a profile. Every column, all optional. */
export interface ProfileUpdate {
  phone?: string | null;
  pronouns?: string | null;
  location?: string | null;
  address?: JsonObject | null;
  links?: JsonObject | null;
  citizenship?: string | null;
  work_authorization?: WorkAuthStatus | null;
  requires_sponsorship?: boolean | null;
  veteran_status?: string | null;
  gender?: string | null;
  race_ethnicity?: string | null;
  disability_status?: string | null;
  clearance?: string | null;
  salary_min?: number | null;
  salary_max?: number | null;
  salary_currency?: string | null;
  remote_preference?: WorkArrangement | null;
  willing_to_relocate?: boolean | null;
  relocation_targets?: string[] | null;
  desired_roles?: string[] | null;
  desired_industries?: string[] | null;
  excluded_companies?: string[] | null;
  excluded_industries?: string[] | null;
  education?: JsonObject[] | null;
  start_date_availability?: IsoDate | null;
  notice_period_weeks?: number | null;
  extra?: JsonObject | null;
}

/** The policy the automation obeys, stored on `users.preferences`. */
export interface PreferencesRead {
  /** 0–100. The ScoreBar's threshold tick is drawn here. */
  min_score: number;
  auto_apply: boolean;
  max_applications_per_day: number;
  max_essay_questions: number;
  min_salary?: number | null;
  preferred_locations: string[];
  preferred_keywords: string[];
  blocked_companies: string[];
  blocked_industries: string[];
  exclude_defense: boolean;
  skip_startups_under?: number | null;
  remote_only: boolean;
  require_no_sponsorship: boolean;
  resume_variant?: string | null;
  resume_template: string;
  cover_letter_policy: CoverLetterPolicy;
  providers_enabled: string[];
}

/** Partial update to preferences. */
export interface PreferencesUpdate {
  min_score?: number | null;
  auto_apply?: boolean | null;
  max_applications_per_day?: number | null;
  max_essay_questions?: number | null;
  min_salary?: number | null;
  preferred_locations?: string[] | null;
  preferred_keywords?: string[] | null;
  blocked_companies?: string[] | null;
  blocked_industries?: string[] | null;
  exclude_defense?: boolean | null;
  skip_startups_under?: number | null;
  remote_only?: boolean | null;
  require_no_sponsorship?: boolean | null;
  resume_variant?: string | null;
  resume_template?: string | null;
  cover_letter_policy?: CoverLetterPolicy | null;
  providers_enabled?: string[] | null;
}

/** A user as returned by `GET /profile`. */
export interface UserRead {
  id: Uuid;
  email: string;
  full_name?: string | null;
  is_active: boolean;
  onboarded_at?: IsoDateTime | null;
  preferences: PreferencesRead;
  profile?: ProfileRead | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/**
 * The safe, readable projection of runtime configuration.
 *
 * Every secret appears as a `*_configured: boolean` rather than as a value — there is no
 * shape of this object that can leak a key, which is why the titlebar safety chip can read
 * from it freely.
 */
export interface SettingsRead {
  app_name: string;
  environment: string;
  debug: boolean;
  data_dir: string;
  database_backend: 'postgresql' | 'sqlite' | 'other';
  sqlite_mode: boolean;
  cache_backend: string;
  cache_default_ttl: number;
  cache_llm_responses: boolean;
  cache_embeddings: boolean;
  llm_provider: string;
  llm_model_reasoning: string;
  llm_model_fast: string;
  llm_model_local: string;
  local_llm_base_url: string;
  llm_max_retries: number;
  llm_timeout_seconds: number;
  llm_daily_token_budget: number;
  anthropic_configured: boolean;
  openai_configured: boolean;
  embedding_provider: string;
  embedding_model: string;
  embedding_dim: number;
  vector_store: string;
  knowledge_chunk_tokens: number;
  knowledge_chunk_overlap: number;
  knowledge_autoindex: boolean;
  knowledge_reindex_interval_minutes: number;
  github_configured: boolean;
  github_include_forks: boolean;
  github_max_repos: number;
  website_crawl_max_pages: number;
  website_crawl_max_depth: number;
  project_scan_max_files: number;
  project_scan_max_file_bytes: number;
  storage_backend: string;
  s3_bucket?: string | null;
  s3_region: string;
  aws_configured: boolean;
  playwright_headless: boolean;
  playwright_slow_mo_ms: number;
  playwright_timeout_ms: number;
  /** Kill switch, half 1. Defaults to the safe position. */
  auto_apply_enabled: boolean;
  /** Kill switch, half 2. Defaults to the safe position. */
  dry_run: boolean;
  /** `auto_apply_enabled && !dry_run`. The titlebar safety chip shows whenever this is false. */
  is_submission_allowed: boolean;
  auto_apply_min_score: number;
  max_applications_per_day: number;
  max_applications_per_session: number;
  max_essay_questions_before_review: number;
  min_answer_confidence: number;
  delete_temp_resume_after_submit: boolean;
  pdf_engine: string;
  latex_binary: string;
  resume_max_pages: number;
  resume_template: string;
  api_host: string;
  api_port: number;
  log_level: string;
  log_json: boolean;
  metrics_enabled: boolean;
  sentry_configured: boolean;
}

/**
 * Partial update to runtime configuration.
 *
 * The secret-bearing fields are write-only: they are accepted here and never echoed back by
 * {@link SettingsRead}. A form that binds them must therefore treat an empty string as
 * "leave unchanged", never as "clear".
 */
export interface SettingsUpdate {
  anthropic_api_key?: string | null;
  openai_api_key?: string | null;
  github_token?: string | null;
  aws_access_key_id?: string | null;
  aws_secret_access_key?: string | null;
  sentry_dsn?: string | null;
  llm_provider?: 'anthropic' | 'openai' | 'local' | 'null' | null;
  llm_model_reasoning?: string | null;
  llm_model_fast?: string | null;
  llm_model_local?: string | null;
  local_llm_base_url?: string | null;
  llm_max_retries?: number | null;
  llm_timeout_seconds?: number | null;
  llm_daily_token_budget?: number | null;
  cache_backend?: 'memory' | 'disk' | 'redis' | null;
  cache_default_ttl?: number | null;
  cache_llm_responses?: boolean | null;
  cache_embeddings?: boolean | null;
  embedding_provider?: 'openai' | 'local' | 'hashing' | null;
  embedding_model?: string | null;
  vector_store?: 'pgvector' | 'sqlite_vec' | 'memory' | null;
  knowledge_chunk_tokens?: number | null;
  knowledge_chunk_overlap?: number | null;
  knowledge_autoindex?: boolean | null;
  knowledge_reindex_interval_minutes?: number | null;
  github_include_forks?: boolean | null;
  github_max_repos?: number | null;
  website_crawl_max_pages?: number | null;
  website_crawl_max_depth?: number | null;
  project_scan_max_files?: number | null;
  project_scan_max_file_bytes?: number | null;
  storage_backend?: 'local' | 's3' | null;
  s3_bucket?: string | null;
  s3_endpoint_url?: string | null;
  s3_region?: string | null;
  playwright_headless?: boolean | null;
  playwright_slow_mo_ms?: number | null;
  playwright_timeout_ms?: number | null;
  auto_apply_enabled?: boolean | null;
  dry_run?: boolean | null;
  auto_apply_min_score?: number | null;
  max_applications_per_day?: number | null;
  max_applications_per_session?: number | null;
  max_essay_questions_before_review?: number | null;
  min_answer_confidence?: number | null;
  delete_temp_resume_after_submit?: boolean | null;
  pdf_engine?: 'latex' | 'docx' | 'html' | null;
  latex_binary?: string | null;
  resume_max_pages?: number | null;
  resume_template?: string | null;
  log_level?: string | null;
  log_json?: boolean | null;
  metrics_enabled?: boolean | null;
}

/** One registered plugin, as reported by `GET /settings/plugins`. */
export interface PluginInfo {
  kind: PluginKind;
  name: string;
  version: string;
  display_name: string;
  description: string;
  author: string;
  capabilities: string[];
  enabled: boolean;
  enabled_by_default: boolean;
  /** `null` unless `?probe=true` — probing costs a live call per plugin. */
  healthy?: boolean | null;
}

/** One rule in the scoring pack — the editable form of `app/config/scoring_rules.yaml`. */
export interface ScoreRuleSchema {
  key: string;
  label: string;
  description?: string | null;
  points: number;
  weight: number;
  category: string;
  enabled: boolean;
  hard_negative: boolean;
  criteria: JsonObject;
}

/** Replacement rule pack — the body of `PUT /settings/scoring-rules`. */
export interface ScoringRulesUpdate {
  rules?: ScoreRuleSchema[];
  reset_to_defaults?: boolean;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Onboarding
// ══════════════════════════════════════════════════════════════════════════════════════

/** One input in a step, described well enough for the client to render it blind. */
export interface OnboardingField {
  name: string;
  label: string;
  kind: FieldKind;
  required: boolean;
  options: JsonObject[];
  placeholder?: string | null;
  help?: string | null;
}

/** One screen of the wizard. */
export interface OnboardingStep {
  key: string;
  title: string;
  description?: string | null;
  fields: OnboardingField[];
  required: boolean;
  complete: boolean;
}

/** Where the user is in the wizard. */
export interface OnboardingStatus {
  complete: boolean;
  current_step?: string | null;
  steps: OnboardingStep[];
  /** 0–1. */
  progress: number;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Logs
// ══════════════════════════════════════════════════════════════════════════════════════

/** One persisted structured log event. */
export interface LogEntryRead {
  id: Uuid;
  level: string;
  event: string;
  logger?: string | null;
  correlation_id?: string | null;
  session_id?: Uuid | null;
  application_id?: Uuid | null;
  posting_id?: Uuid | null;
  payload: JsonObject;
  at: IsoDateTime;
  created_at: IsoDateTime;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Status sync — docs/CONTRACTS.md §17
// ══════════════════════════════════════════════════════════════════════════════════════

/** A connected mailbox as the desktop app sees it. Credentials never appear here. */
export interface EmailAccountRead {
  id: Uuid;
  user_id: Uuid;
  provider: MailProvider;
  address: string;
  enabled: boolean;
  /** Whether a credential reference resolves in the OS keychain. */
  connected: boolean;
  last_sync_at?: IsoDateTime | null;
  folders: string[];
  last_error?: string | null;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/**
 * Body of `POST /tracking/accounts` — connect one mailbox, read-only.
 *
 * `secret` is forwarded straight to the OS keychain and never persisted in the database
 * (§17.8 invariant 4). It is write-only and never echoed back.
 */
export interface EmailAccountCreate {
  provider: MailProvider;
  address: string;
  secret?: string | null;
  folders?: string[];
  enabled?: boolean;
}

/** One classified message that says something about an application's outcome. */
export interface StatusSignalRead {
  id: Uuid;
  user_id: Uuid;
  application_id?: Uuid | null;
  source: SignalSource;
  kind: SignalKind;
  external_ref: string;
  sender: string;
  sender_domain: string;
  subject: string;
  /** Capped at 500 characters server-side; full bodies are never persisted. */
  snippet: string;
  received_at: IsoDateTime;
  detected_status?: ApplicationStatus | null;
  confidence: number;
  applied: boolean;
  needs_review: boolean;
  match_evidence: JsonObject;
  created_at: IsoDateTime;
  updated_at: IsoDateTime;
}

/** Body of `POST /tracking/signals/{id}/resolve` — a human's decision about a signal. */
export interface SignalResolve {
  application_id: Uuid;
  status: ApplicationStatus;
}

/** Body of `POST /tracking/sync` — run a sync now. */
export interface SyncRequest {
  account_id?: Uuid | null;
  since?: IsoDateTime | null;
}

/** Aggregate status-sync state — what the tracking panel renders in one request. */
export interface TrackingStats {
  accounts: number;
  accounts_enabled: number;
  signals_total: number;
  signals_applied: number;
  signals_pending_review: number;
  signals_by_kind: Record<string, number>;
  applications_synced: number;
  last_sync_at?: IsoDateTime | null;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Query parameter shapes
// ══════════════════════════════════════════════════════════════════════════════════════

/** Offset/limit pagination, accepted by every list endpoint. */
export interface PageParams {
  limit?: number;
  offset?: number;
}

/**
 * Filters accepted by `GET /applications` and `GET /reviews` (identical signatures).
 *
 * Every field is optional and nullable-free on purpose: `undefined` means "not filtering",
 * and `normalizeFilters` in `lib/query/keys.ts` strips it before the key is hashed. Adding a
 * `| null` here would reintroduce exactly the cache fragmentation §10.4 warns about.
 */
export interface ApplicationFilters extends PageParams {
  q?: string;
  status?: ApplicationStatus;
  provider?: ATSProviderName;
  company?: string;
  session_id?: Uuid;
  review_reason?: ReviewReason;
  needs_review?: boolean;
  since?: IsoDateTime;
  until?: IsoDateTime;
}

/** Filters accepted by `GET /postings`. */
export interface PostingFilters extends PageParams {
  q?: string;
  provider?: ATSProviderName;
  status?: PostingStatus;
  min_score?: number;
  company?: string;
  since?: IsoDateTime;
  remote_only?: boolean;
}

/** Filters accepted by `GET /knowledge/facts`. */
export interface FactFilters extends PageParams {
  q?: string;
  kind?: FactKind;
  organization?: string;
  role?: string;
  skill?: string;
  active?: boolean;
  verified?: boolean;
  min_impact?: number;
  min_confidence?: number;
}

/** Filters accepted by `GET /knowledge/entities`. */
export interface EntityFilters extends PageParams {
  kind?: EntityKind;
}

/** Filters accepted by `GET /knowledge/graph`. */
export interface GraphFilters {
  /** Comma-joined {@link EntityKind} values; the client joins, the server splits. */
  kinds?: string;
  limit?: number;
}

/** Filters accepted by `GET /logs` (historical search only — the live tail is a ring buffer). */
export interface LogFilters extends PageParams {
  level?: string;
  event?: string;
  correlation_id?: string;
  session_id?: Uuid;
  application_id?: Uuid;
  since?: IsoDateTime;
}

/** Filters accepted by `GET /tracking/signals`. */
export interface SignalFilters extends PageParams {
  source?: SignalSource;
  kind?: SignalKind;
  application_id?: Uuid;
  applied?: boolean;
  needs_review?: boolean;
  since?: IsoDateTime;
  until?: IsoDateTime;
}

/** Filters accepted by `GET /settings/plugins`. */
export interface PluginFilters {
  kind?: PluginKind;
  /** Probing costs one live call per plugin; off by default. */
  probe?: boolean;
}

// ══════════════════════════════════════════════════════════════════════════════════════
// Event stream — GET /ws (docs/CONTRACTS.md §14 and §17.7)
// ══════════════════════════════════════════════════════════════════════════════════════

/**
 * Every event name the bus may publish. Closed by contract (`EVENT_NAMES` in
 * `app/api/events.py`): publishing an unlisted name is refused server-side, so a `default`
 * branch in the client handles only future versions, never a typo.
 */
export const EVENT_NAMES = [
  'session.started',
  'session.updated',
  'session.finished',
  'posting.discovered',
  'posting.scored',
  'application.created',
  'application.status_changed',
  'application.submitted',
  'application.needs_review',
  'knowledge.index_started',
  'knowledge.index_progress',
  'knowledge.index_finished',
  'tracking.sync_started',
  'tracking.sync_progress',
  'tracking.signal_found',
  'tracking.status_changed',
  'tracking.sync_finished',
  'log.entry',
] as const;
export type EventName = (typeof EVENT_NAMES)[number];

/** One broadcast frame, as rendered by `Event.to_wire()`. */
export interface EventFrame<N extends EventName = EventName, P = unknown> {
  event: N;
  payload: P;
  /** Monotonic per-process counter. A gap means the client fell behind and was trimmed. */
  sequence: number;
  at: IsoDateTime;
}

/** Payload of `posting.discovered` — `DiscoveryReport.as_dict()` plus run context. */
export interface DiscoveryReportPayload {
  found: number;
  created: number;
  deduped: number;
  scored: number;
  skipped: number;
  errors: string[];
  by_provider: Record<string, number>;
  /**
   * Boards each provider was asked to poll. Pair it with `by_provider` to tell "nowhere to
   * look" apart from "looked everywhere and found nothing" — a bare `0` reads the same in
   * both cases.
   */
  boards_by_provider: Record<string, number>;
  /** Providers that answered without error and produced nothing. */
  empty_providers: string[];
  duration_seconds: number;
  provider?: string;
  user_id?: Uuid;
  queued_for_apply?: number;
}

/** Payload of `knowledge.index_started`. Carries whichever scope the run has. */
export interface KnowledgeIndexStartedPayload {
  source_id?: Uuid;
  user_id?: Uuid;
  force: boolean;
}

/** Payload of `knowledge.index_progress`. */
export interface KnowledgeIndexProgressPayload {
  source_id?: Uuid;
  user_id?: Uuid;
  /** 0–1 when the total is known; absent when it is not (use an IndeterminateBar then). */
  progress?: number;
  documents?: number;
  chunks?: number;
}

/**
 * Payload of `knowledge.index_finished` — a single {@link IndexReport} for one source, or
 * the folded summary when a whole user was re-indexed.
 */
export type KnowledgeIndexFinishedPayload =
  | IndexReport
  | {
      sources: number;
      skipped: number;
      failed: number;
      documents: number;
      chunks: number;
      facts: number;
      reports: IndexReport[];
      user_id?: Uuid;
    };

/** Payload of `tracking.sync_started`. */
export interface TrackingSyncStartedPayload {
  account_id: Uuid;
  provider: string;
}

/** Payload of `tracking.sync_progress` and `tracking.sync_finished` — `SyncReport.as_dict()`. */
export interface TrackingSyncReportPayload {
  account_id?: Uuid | null;
  fetched: number;
  classified: number;
  matched: number;
  applied: number;
  needs_review: number;
  skipped: number;
  duration_seconds: number;
  errors: string[];
}

/** Payload of `tracking.signal_found`. */
export interface TrackingSignalFoundPayload {
  id: Uuid;
  kind: SignalKind;
  application_id?: Uuid | null;
  confidence: number;
}

/** Payload of `tracking.status_changed`. */
export interface TrackingStatusChangedPayload {
  application_id: Uuid;
  status: ApplicationStatus;
  source: StatusSource;
  confidence: number;
  signal_id: Uuid;
}

/**
 * The discriminated union of every frame the client may receive.
 *
 * The entity-carrying members are what make `setQueryData` possible without a refetch: the
 * payload is byte-for-byte what the corresponding REST endpoint returns. The rest are
 * payload-less in the §10.8 sense — they carry counters, not entities, and are handled by a
 * narrow `invalidateQueries`.
 */
export type AppEvent =
  | EventFrame<'session.started', SessionRead>
  | EventFrame<'session.updated', SessionRead>
  | EventFrame<'session.finished', SessionRead>
  | EventFrame<'posting.discovered', DiscoveryReportPayload>
  | EventFrame<'posting.scored', ScoreRead>
  | EventFrame<'application.created', ApplicationRead>
  | EventFrame<'application.status_changed', ApplicationRead>
  | EventFrame<'application.submitted', ApplicationRead>
  | EventFrame<'application.needs_review', ApplicationRead>
  | EventFrame<'knowledge.index_started', KnowledgeIndexStartedPayload>
  | EventFrame<'knowledge.index_progress', KnowledgeIndexProgressPayload>
  | EventFrame<'knowledge.index_finished', KnowledgeIndexFinishedPayload>
  | EventFrame<'tracking.sync_started', TrackingSyncStartedPayload>
  | EventFrame<'tracking.sync_progress', TrackingSyncReportPayload>
  | EventFrame<'tracking.signal_found', TrackingSignalFoundPayload>
  | EventFrame<'tracking.status_changed', TrackingStatusChangedPayload>
  | EventFrame<'tracking.sync_finished', TrackingSyncReportPayload>
  | EventFrame<'log.entry', LogEntryRead>;

/** The subset of {@link AppEvent} whose payload is an `ApplicationRead`. */
export type ApplicationEventName = Extract<AppEvent, { payload: ApplicationRead }>['event'];

/** The subset of {@link AppEvent} whose payload is a `SessionRead`. */
export type SessionEventName = Extract<AppEvent, { payload: SessionRead }>['event'];
